// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: servers/gateway/proto/adapter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientMessage_MessageType int32

const (
	ClientMessage_REQUEST  ClientMessage_MessageType = 0
	ClientMessage_RESPONSE ClientMessage_MessageType = 1
	ClientMessage_ASYNC    ClientMessage_MessageType = 2
)

// Enum value maps for ClientMessage_MessageType.
var (
	ClientMessage_MessageType_name = map[int32]string{
		0: "REQUEST",
		1: "RESPONSE",
		2: "ASYNC",
	}
	ClientMessage_MessageType_value = map[string]int32{
		"REQUEST":  0,
		"RESPONSE": 1,
		"ASYNC":    2,
	}
)

func (x ClientMessage_MessageType) Enum() *ClientMessage_MessageType {
	p := new(ClientMessage_MessageType)
	*p = x
	return p
}

func (x ClientMessage_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientMessage_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_servers_gateway_proto_adapter_proto_enumTypes[0].Descriptor()
}

func (ClientMessage_MessageType) Type() protoreflect.EnumType {
	return &file_servers_gateway_proto_adapter_proto_enumTypes[0]
}

func (x ClientMessage_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientMessage_MessageType.Descriptor instead.
func (ClientMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_servers_gateway_proto_adapter_proto_rawDescGZIP(), []int{0, 0}
}

type ClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Meta   map[string]string         `protobuf:"bytes,2,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body   []byte                    `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Nodeid string                    `protobuf:"bytes,4,opt,name=nodeid,proto3" json:"nodeid,omitempty"`
	Typ    ClientMessage_MessageType `protobuf:"varint,5,opt,name=typ,proto3,enum=adapter.ClientMessage_MessageType" json:"typ,omitempty"`
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_gateway_proto_adapter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_servers_gateway_proto_adapter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_servers_gateway_proto_adapter_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientMessage) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ClientMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClientMessage) GetNodeid() string {
	if x != nil {
		return x.Nodeid
	}
	return ""
}

func (x *ClientMessage) GetTyp() ClientMessage_MessageType {
	if x != nil {
		return x.Typ
	}
	return ClientMessage_REQUEST
}

type UserMessageWraper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gateway      string            `protobuf:"bytes,1,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Name         string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Meta         map[string]string `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body         []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	UserId       uint64            `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SerialNumber string            `protobuf:"bytes,6,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
}

func (x *UserMessageWraper) Reset() {
	*x = UserMessageWraper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_gateway_proto_adapter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMessageWraper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessageWraper) ProtoMessage() {}

func (x *UserMessageWraper) ProtoReflect() protoreflect.Message {
	mi := &file_servers_gateway_proto_adapter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessageWraper.ProtoReflect.Descriptor instead.
func (*UserMessageWraper) Descriptor() ([]byte, []int) {
	return file_servers_gateway_proto_adapter_proto_rawDescGZIP(), []int{1}
}

func (x *UserMessageWraper) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *UserMessageWraper) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserMessageWraper) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *UserMessageWraper) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *UserMessageWraper) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserMessageWraper) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

type SteamClosed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SteamClosed) Reset() {
	*x = SteamClosed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_gateway_proto_adapter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SteamClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SteamClosed) ProtoMessage() {}

func (x *SteamClosed) ProtoReflect() protoreflect.Message {
	mi := &file_servers_gateway_proto_adapter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SteamClosed.ProtoReflect.Descriptor instead.
func (*SteamClosed) Descriptor() ([]byte, []int) {
	return file_servers_gateway_proto_adapter_proto_rawDescGZIP(), []int{2}
}

func (x *SteamClosed) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_servers_gateway_proto_adapter_proto protoreflect.FileDescriptor

var file_servers_gateway_proto_adapter_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x22, 0xa9,
	0x02, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x03, 0x74, 0x79, 0x70, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03, 0x74, 0x79, 0x70, 0x1a, 0x37, 0x0a, 0x09,
	0x4d, 0x65, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x33, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x41, 0x53, 0x59, 0x4e, 0x43, 0x10, 0x02, 0x22, 0x86, 0x02, 0x0a, 0x11, 0x55,
	0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x72, 0x61, 0x70, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x38,
	0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61,
	0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x57, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x37, 0x0a, 0x09, 0x4d, 0x65,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x1f, 0x0a, 0x0b, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x32, 0x9c, 0x01, 0x0a, 0x0b, 0x47, 0x61, 0x74, 0x65, 0x41, 0x64, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1a, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x72, 0x61, 0x70, 0x65, 0x72, 0x1a,
	0x14, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x64, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1a, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x72, 0x61, 0x70, 0x65,
	0x72, 0x1a, 0x1a, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x72, 0x61, 0x70, 0x65, 0x72, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x1f, 0x5a, 0x1d, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73,
	0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_servers_gateway_proto_adapter_proto_rawDescOnce sync.Once
	file_servers_gateway_proto_adapter_proto_rawDescData = file_servers_gateway_proto_adapter_proto_rawDesc
)

func file_servers_gateway_proto_adapter_proto_rawDescGZIP() []byte {
	file_servers_gateway_proto_adapter_proto_rawDescOnce.Do(func() {
		file_servers_gateway_proto_adapter_proto_rawDescData = protoimpl.X.CompressGZIP(file_servers_gateway_proto_adapter_proto_rawDescData)
	})
	return file_servers_gateway_proto_adapter_proto_rawDescData
}

var file_servers_gateway_proto_adapter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_servers_gateway_proto_adapter_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_servers_gateway_proto_adapter_proto_goTypes = []interface{}{
	(ClientMessage_MessageType)(0), // 0: adapter.ClientMessage.MessageType
	(*ClientMessage)(nil),          // 1: adapter.ClientMessage
	(*UserMessageWraper)(nil),      // 2: adapter.UserMessageWraper
	(*SteamClosed)(nil),            // 3: adapter.SteamClosed
	nil,                            // 4: adapter.ClientMessage.MetaEntry
	nil,                            // 5: adapter.UserMessageWraper.MetaEntry
}
var file_servers_gateway_proto_adapter_proto_depIdxs = []int32{
	4, // 0: adapter.ClientMessage.meta:type_name -> adapter.ClientMessage.MetaEntry
	0, // 1: adapter.ClientMessage.typ:type_name -> adapter.ClientMessage.MessageType
	5, // 2: adapter.UserMessageWraper.meta:type_name -> adapter.UserMessageWraper.MetaEntry
	2, // 3: adapter.GateAdapter.UserMessage:input_type -> adapter.UserMessageWraper
	2, // 4: adapter.GateAdapter.UserStream:input_type -> adapter.UserMessageWraper
	3, // 5: adapter.GateAdapter.UserMessage:output_type -> adapter.SteamClosed
	2, // 6: adapter.GateAdapter.UserStream:output_type -> adapter.UserMessageWraper
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_servers_gateway_proto_adapter_proto_init() }
func file_servers_gateway_proto_adapter_proto_init() {
	if File_servers_gateway_proto_adapter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_servers_gateway_proto_adapter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_gateway_proto_adapter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMessageWraper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_gateway_proto_adapter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SteamClosed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_servers_gateway_proto_adapter_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servers_gateway_proto_adapter_proto_goTypes,
		DependencyIndexes: file_servers_gateway_proto_adapter_proto_depIdxs,
		EnumInfos:         file_servers_gateway_proto_adapter_proto_enumTypes,
		MessageInfos:      file_servers_gateway_proto_adapter_proto_msgTypes,
	}.Build()
	File_servers_gateway_proto_adapter_proto = out.File
	file_servers_gateway_proto_adapter_proto_rawDesc = nil
	file_servers_gateway_proto_adapter_proto_goTypes = nil
	file_servers_gateway_proto_adapter_proto_depIdxs = nil
}
