// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: adapter.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GateAdapterClient is the client API for GateAdapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GateAdapterClient interface {
	UserEvent(ctx context.Context, in *AsyncMessageWraper, opts ...grpc.CallOption) (*SteamClosed, error)
	EventStream(ctx context.Context, opts ...grpc.CallOption) (GateAdapter_EventStreamClient, error)
}

type gateAdapterClient struct {
	cc grpc.ClientConnInterface
}

func NewGateAdapterClient(cc grpc.ClientConnInterface) GateAdapterClient {
	return &gateAdapterClient{cc}
}

func (c *gateAdapterClient) UserEvent(ctx context.Context, in *AsyncMessageWraper, opts ...grpc.CallOption) (*SteamClosed, error) {
	out := new(SteamClosed)
	err := c.cc.Invoke(ctx, "/adapter.GateAdapter/UserEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateAdapterClient) EventStream(ctx context.Context, opts ...grpc.CallOption) (GateAdapter_EventStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &GateAdapter_ServiceDesc.Streams[0], "/adapter.GateAdapter/EventStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &gateAdapterEventStreamClient{stream}
	return x, nil
}

type GateAdapter_EventStreamClient interface {
	Send(*AsyncMessageWraper) error
	Recv() (*AsyncMessageWraper, error)
	grpc.ClientStream
}

type gateAdapterEventStreamClient struct {
	grpc.ClientStream
}

func (x *gateAdapterEventStreamClient) Send(m *AsyncMessageWraper) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gateAdapterEventStreamClient) Recv() (*AsyncMessageWraper, error) {
	m := new(AsyncMessageWraper)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GateAdapterServer is the server API for GateAdapter service.
// All implementations must embed UnimplementedGateAdapterServer
// for forward compatibility
type GateAdapterServer interface {
	UserEvent(context.Context, *AsyncMessageWraper) (*SteamClosed, error)
	EventStream(GateAdapter_EventStreamServer) error
	mustEmbedUnimplementedGateAdapterServer()
}

// UnimplementedGateAdapterServer must be embedded to have forward compatible implementations.
type UnimplementedGateAdapterServer struct {
}

func (UnimplementedGateAdapterServer) UserEvent(context.Context, *AsyncMessageWraper) (*SteamClosed, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserEvent not implemented")
}
func (UnimplementedGateAdapterServer) EventStream(GateAdapter_EventStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method EventStream not implemented")
}
func (UnimplementedGateAdapterServer) mustEmbedUnimplementedGateAdapterServer() {}

// UnsafeGateAdapterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GateAdapterServer will
// result in compilation errors.
type UnsafeGateAdapterServer interface {
	mustEmbedUnimplementedGateAdapterServer()
}

func RegisterGateAdapterServer(s grpc.ServiceRegistrar, srv GateAdapterServer) {
	s.RegisterService(&GateAdapter_ServiceDesc, srv)
}

func _GateAdapter_UserEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AsyncMessageWraper)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateAdapterServer).UserEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adapter.GateAdapter/UserEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateAdapterServer).UserEvent(ctx, req.(*AsyncMessageWraper))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateAdapter_EventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GateAdapterServer).EventStream(&gateAdapterEventStreamServer{stream})
}

type GateAdapter_EventStreamServer interface {
	Send(*AsyncMessageWraper) error
	Recv() (*AsyncMessageWraper, error)
	grpc.ServerStream
}

type gateAdapterEventStreamServer struct {
	grpc.ServerStream
}

func (x *gateAdapterEventStreamServer) Send(m *AsyncMessageWraper) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gateAdapterEventStreamServer) Recv() (*AsyncMessageWraper, error) {
	m := new(AsyncMessageWraper)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GateAdapter_ServiceDesc is the grpc.ServiceDesc for GateAdapter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GateAdapter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adapter.GateAdapter",
	HandlerType: (*GateAdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserEvent",
			Handler:    _GateAdapter_UserEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventStream",
			Handler:       _GateAdapter_EventStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "adapter.proto",
}
