// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: gateway.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GatewayClient is the client API for Gateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayClient interface {
	SendMessageToUse(ctx context.Context, in *SendMessageToUserRequest, opts ...grpc.CallOption) (*SendMessageToUserResponse, error)
	ProxyServer(ctx context.Context, in *ProxyServerRequest, opts ...grpc.CallOption) (*ProxyServerResponse, error)
}

type gatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayClient(cc grpc.ClientConnInterface) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) SendMessageToUse(ctx context.Context, in *SendMessageToUserRequest, opts ...grpc.CallOption) (*SendMessageToUserResponse, error) {
	out := new(SendMessageToUserResponse)
	err := c.cc.Invoke(ctx, "/gateway.Gateway/SendMessageToUse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) ProxyServer(ctx context.Context, in *ProxyServerRequest, opts ...grpc.CallOption) (*ProxyServerResponse, error) {
	out := new(ProxyServerResponse)
	err := c.cc.Invoke(ctx, "/gateway.Gateway/ProxyServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServer is the server API for Gateway service.
// All implementations must embed UnimplementedGatewayServer
// for forward compatibility
type GatewayServer interface {
	SendMessageToUse(context.Context, *SendMessageToUserRequest) (*SendMessageToUserResponse, error)
	ProxyServer(context.Context, *ProxyServerRequest) (*ProxyServerResponse, error)
	mustEmbedUnimplementedGatewayServer()
}

// UnimplementedGatewayServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayServer struct {
}

func (UnimplementedGatewayServer) SendMessageToUse(context.Context, *SendMessageToUserRequest) (*SendMessageToUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessageToUse not implemented")
}
func (UnimplementedGatewayServer) ProxyServer(context.Context, *ProxyServerRequest) (*ProxyServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProxyServer not implemented")
}
func (UnimplementedGatewayServer) mustEmbedUnimplementedGatewayServer() {}

// UnsafeGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServer will
// result in compilation errors.
type UnsafeGatewayServer interface {
	mustEmbedUnimplementedGatewayServer()
}

func RegisterGatewayServer(s grpc.ServiceRegistrar, srv GatewayServer) {
	s.RegisterService(&Gateway_ServiceDesc, srv)
}

func _Gateway_SendMessageToUse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageToUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).SendMessageToUse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.Gateway/SendMessageToUse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).SendMessageToUse(ctx, req.(*SendMessageToUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_ProxyServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).ProxyServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.Gateway/ProxyServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).ProxyServer(ctx, req.(*ProxyServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gateway_ServiceDesc is the grpc.ServiceDesc for Gateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessageToUse",
			Handler:    _Gateway_SendMessageToUse_Handler,
		},
		{
			MethodName: "ProxyServer",
			Handler:    _Gateway_ProxyServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
