// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: servers/gateway/proto/gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginResponse_Flag int32

const (
	LoginResponse_Success LoginResponse_Flag = 0
)

// Enum value maps for LoginResponse_Flag.
var (
	LoginResponse_Flag_name = map[int32]string{
		0: "Success",
	}
	LoginResponse_Flag_value = map[string]int32{
		"Success": 0,
	}
)

func (x LoginResponse_Flag) Enum() *LoginResponse_Flag {
	p := new(LoginResponse_Flag)
	*p = x
	return p
}

func (x LoginResponse_Flag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginResponse_Flag) Descriptor() protoreflect.EnumDescriptor {
	return file_servers_gateway_proto_gateway_proto_enumTypes[0].Descriptor()
}

func (LoginResponse_Flag) Type() protoreflect.EnumType {
	return &file_servers_gateway_proto_gateway_proto_enumTypes[0]
}

func (x LoginResponse_Flag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginResponse_Flag.Descriptor instead.
func (LoginResponse_Flag) EnumDescriptor() ([]byte, []int) {
	return file_servers_gateway_proto_gateway_proto_rawDescGZIP(), []int{7, 0}
}

type SendMessageToUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SendMessageToUserRequest) Reset() {
	*x = SendMessageToUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_gateway_proto_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageToUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageToUserRequest) ProtoMessage() {}

func (x *SendMessageToUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_gateway_proto_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageToUserRequest.ProtoReflect.Descriptor instead.
func (*SendMessageToUserRequest) Descriptor() ([]byte, []int) {
	return file_servers_gateway_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageToUserRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SendMessageToUserRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendMessageToUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendMessageToUserResponse) Reset() {
	*x = SendMessageToUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_gateway_proto_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageToUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageToUserResponse) ProtoMessage() {}

func (x *SendMessageToUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servers_gateway_proto_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageToUserResponse.ProtoReflect.Descriptor instead.
func (*SendMessageToUserResponse) Descriptor() ([]byte, []int) {
	return file_servers_gateway_proto_gateway_proto_rawDescGZIP(), []int{1}
}

type CaptchaQuestion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaptchId   string `protobuf:"bytes,1,opt,name=captch_id,json=captchId,proto3" json:"captch_id,omitempty"`
	CaptchType string `protobuf:"bytes,2,opt,name=captch_type,json=captchType,proto3" json:"captch_type,omitempty"`
	CatpchRaw  []byte `protobuf:"bytes,3,opt,name=catpch_raw,json=catpchRaw,proto3" json:"catpch_raw,omitempty"`
}

func (x *CaptchaQuestion) Reset() {
	*x = CaptchaQuestion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_gateway_proto_gateway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptchaQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaQuestion) ProtoMessage() {}

func (x *CaptchaQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_servers_gateway_proto_gateway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaQuestion.ProtoReflect.Descriptor instead.
func (*CaptchaQuestion) Descriptor() ([]byte, []int) {
	return file_servers_gateway_proto_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *CaptchaQuestion) GetCaptchId() string {
	if x != nil {
		return x.CaptchId
	}
	return ""
}

func (x *CaptchaQuestion) GetCaptchType() string {
	if x != nil {
		return x.CaptchType
	}
	return ""
}

func (x *CaptchaQuestion) GetCatpchRaw() []byte {
	if x != nil {
		return x.CatpchRaw
	}
	return nil
}

type CaptchaAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaptchId   string `protobuf:"bytes,1,opt,name=captch_id,json=captchId,proto3" json:"captch_id,omitempty"`
	CaptchType string `protobuf:"bytes,2,opt,name=captch_type,json=captchType,proto3" json:"captch_type,omitempty"`
	Answer     string `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *CaptchaAnswer) Reset() {
	*x = CaptchaAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_gateway_proto_gateway_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptchaAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaAnswer) ProtoMessage() {}

func (x *CaptchaAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_servers_gateway_proto_gateway_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaAnswer.ProtoReflect.Descriptor instead.
func (*CaptchaAnswer) Descriptor() ([]byte, []int) {
	return file_servers_gateway_proto_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *CaptchaAnswer) GetCaptchId() string {
	if x != nil {
		return x.CaptchId
	}
	return ""
}

func (x *CaptchaAnswer) GetCaptchType() string {
	if x != nil {
		return x.CaptchType
	}
	return ""
}

func (x *CaptchaAnswer) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type AccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string         `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Passwd  string         `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	Answer  *CaptchaAnswer `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_gateway_proto_gateway_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_servers_gateway_proto_gateway_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_servers_gateway_proto_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *AccountInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AccountInfo) GetPasswd() string {
	if x != nil {
		return x.Passwd
	}
	return ""
}

func (x *AccountInfo) GetAnswer() *CaptchaAnswer {
	if x != nil {
		return x.Answer
	}
	return nil
}

type SessionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Session string `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_gateway_proto_gateway_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_servers_gateway_proto_gateway_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_servers_gateway_proto_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *SessionInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SessionInfo) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Checker:
	//	*LoginRequest_AccountInfo
	//	*LoginRequest_SessionInfo
	Checker isLoginRequest_Checker `protobuf_oneof:"checker"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_gateway_proto_gateway_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_gateway_proto_gateway_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_servers_gateway_proto_gateway_proto_rawDescGZIP(), []int{6}
}

func (m *LoginRequest) GetChecker() isLoginRequest_Checker {
	if m != nil {
		return m.Checker
	}
	return nil
}

func (x *LoginRequest) GetAccountInfo() *AccountInfo {
	if x, ok := x.GetChecker().(*LoginRequest_AccountInfo); ok {
		return x.AccountInfo
	}
	return nil
}

func (x *LoginRequest) GetSessionInfo() *SessionInfo {
	if x, ok := x.GetChecker().(*LoginRequest_SessionInfo); ok {
		return x.SessionInfo
	}
	return nil
}

type isLoginRequest_Checker interface {
	isLoginRequest_Checker()
}

type LoginRequest_AccountInfo struct {
	AccountInfo *AccountInfo `protobuf:"bytes,1,opt,name=account_info,json=accountInfo,proto3,oneof"`
}

type LoginRequest_SessionInfo struct {
	SessionInfo *SessionInfo `protobuf:"bytes,2,opt,name=session_info,json=sessionInfo,proto3,oneof"`
}

func (*LoginRequest_AccountInfo) isLoginRequest_Checker() {}

func (*LoginRequest_SessionInfo) isLoginRequest_Checker() {}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag LoginResponse_Flag `protobuf:"varint,1,opt,name=flag,proto3,enum=gateway.LoginResponse_Flag" json:"flag,omitempty"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_gateway_proto_gateway_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servers_gateway_proto_gateway_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_servers_gateway_proto_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *LoginResponse) GetFlag() LoginResponse_Flag {
	if x != nil {
		return x.Flag
	}
	return LoginResponse_Success
}

var File_servers_gateway_proto_gateway_proto protoreflect.FileDescriptor

var file_servers_gateway_proto_gateway_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x22, 0x46,
	0x0a, 0x18, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x6e, 0x0a, 0x0f, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x70, 0x74, 0x63,
	0x68, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x70, 0x63, 0x68, 0x5f, 0x72,
	0x61, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x61, 0x74, 0x70, 0x63, 0x68,
	0x52, 0x61, 0x77, 0x22, 0x65, 0x0a, 0x0d, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x6f, 0x0a, 0x0b, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x41, 0x0a, 0x0b, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x8f,
	0x01, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x39, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x0b, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x39, 0x0a, 0x0c, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72,
	0x22, 0x55, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1b, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x04, 0x66, 0x6c,
	0x61, 0x67, 0x22, 0x13, 0x0a, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x32, 0x66, 0x0a, 0x07, 0x47, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x12, 0x5b, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x12, 0x21, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x1f, 0x5a, 0x1d, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_servers_gateway_proto_gateway_proto_rawDescOnce sync.Once
	file_servers_gateway_proto_gateway_proto_rawDescData = file_servers_gateway_proto_gateway_proto_rawDesc
)

func file_servers_gateway_proto_gateway_proto_rawDescGZIP() []byte {
	file_servers_gateway_proto_gateway_proto_rawDescOnce.Do(func() {
		file_servers_gateway_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_servers_gateway_proto_gateway_proto_rawDescData)
	})
	return file_servers_gateway_proto_gateway_proto_rawDescData
}

var file_servers_gateway_proto_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_servers_gateway_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_servers_gateway_proto_gateway_proto_goTypes = []interface{}{
	(LoginResponse_Flag)(0),           // 0: gateway.LoginResponse.Flag
	(*SendMessageToUserRequest)(nil),  // 1: gateway.SendMessageToUserRequest
	(*SendMessageToUserResponse)(nil), // 2: gateway.SendMessageToUserResponse
	(*CaptchaQuestion)(nil),           // 3: gateway.CaptchaQuestion
	(*CaptchaAnswer)(nil),             // 4: gateway.CaptchaAnswer
	(*AccountInfo)(nil),               // 5: gateway.AccountInfo
	(*SessionInfo)(nil),               // 6: gateway.SessionInfo
	(*LoginRequest)(nil),              // 7: gateway.LoginRequest
	(*LoginResponse)(nil),             // 8: gateway.LoginResponse
}
var file_servers_gateway_proto_gateway_proto_depIdxs = []int32{
	4, // 0: gateway.AccountInfo.answer:type_name -> gateway.CaptchaAnswer
	5, // 1: gateway.LoginRequest.account_info:type_name -> gateway.AccountInfo
	6, // 2: gateway.LoginRequest.session_info:type_name -> gateway.SessionInfo
	0, // 3: gateway.LoginResponse.flag:type_name -> gateway.LoginResponse.Flag
	1, // 4: gateway.Gateway.SendMessageToUse:input_type -> gateway.SendMessageToUserRequest
	2, // 5: gateway.Gateway.SendMessageToUse:output_type -> gateway.SendMessageToUserResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_servers_gateway_proto_gateway_proto_init() }
func file_servers_gateway_proto_gateway_proto_init() {
	if File_servers_gateway_proto_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_servers_gateway_proto_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageToUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_gateway_proto_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageToUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_gateway_proto_gateway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptchaQuestion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_gateway_proto_gateway_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptchaAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_gateway_proto_gateway_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_gateway_proto_gateway_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_gateway_proto_gateway_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_gateway_proto_gateway_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_servers_gateway_proto_gateway_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*LoginRequest_AccountInfo)(nil),
		(*LoginRequest_SessionInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_servers_gateway_proto_gateway_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servers_gateway_proto_gateway_proto_goTypes,
		DependencyIndexes: file_servers_gateway_proto_gateway_proto_depIdxs,
		EnumInfos:         file_servers_gateway_proto_gateway_proto_enumTypes,
		MessageInfos:      file_servers_gateway_proto_gateway_proto_msgTypes,
	}.Build()
	File_servers_gateway_proto_gateway_proto = out.File
	file_servers_gateway_proto_gateway_proto_rawDesc = nil
	file_servers_gateway_proto_gateway_proto_goTypes = nil
	file_servers_gateway_proto_gateway_proto_depIdxs = nil
}
