// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: service/gateway/proto/client.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_Aync     MessageType = 0
	MessageType_Request  MessageType = 1
	MessageType_Response MessageType = 2
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "Aync",
		1: "Request",
		2: "Response",
	}
	MessageType_value = map[string]int32{
		"Aync":     0,
		"Request":  1,
		"Response": 2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_gateway_proto_client_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_service_gateway_proto_client_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_service_gateway_proto_client_proto_rawDescGZIP(), []int{0}
}

type LoginResponse_Flag int32

const (
	LoginResponse_Success     LoginResponse_Flag = 0
	LoginResponse_UnknowError LoginResponse_Flag = 1
)

// Enum value maps for LoginResponse_Flag.
var (
	LoginResponse_Flag_name = map[int32]string{
		0: "Success",
		1: "UnknowError",
	}
	LoginResponse_Flag_value = map[string]int32{
		"Success":     0,
		"UnknowError": 1,
	}
)

func (x LoginResponse_Flag) Enum() *LoginResponse_Flag {
	p := new(LoginResponse_Flag)
	*p = x
	return p
}

func (x LoginResponse_Flag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginResponse_Flag) Descriptor() protoreflect.EnumDescriptor {
	return file_service_gateway_proto_client_proto_enumTypes[1].Descriptor()
}

func (LoginResponse_Flag) Type() protoreflect.EnumType {
	return &file_service_gateway_proto_client_proto_enumTypes[1]
}

func (x LoginResponse_Flag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginResponse_Flag.Descriptor instead.
func (LoginResponse_Flag) EnumDescriptor() ([]byte, []int) {
	return file_service_gateway_proto_client_proto_rawDescGZIP(), []int{7, 0}
}

type ClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Body    []byte      `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Msgid   int64       `protobuf:"varint,3,opt,name=msgid,proto3" json:"msgid,omitempty"`
	Msgtype MessageType `protobuf:"varint,4,opt,name=msgtype,proto3,enum=gateway.MessageType" json:"msgtype,omitempty"`
	// Types that are assignable to Endpoint:
	//	*ClientMessage_Nodeid
	//	*ClientMessage_Server
	Endpoint isClientMessage_Endpoint `protobuf_oneof:"endpoint"`
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_client_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClientMessage) GetMsgid() int64 {
	if x != nil {
		return x.Msgid
	}
	return 0
}

func (x *ClientMessage) GetMsgtype() MessageType {
	if x != nil {
		return x.Msgtype
	}
	return MessageType_Aync
}

func (m *ClientMessage) GetEndpoint() isClientMessage_Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

func (x *ClientMessage) GetNodeid() string {
	if x, ok := x.GetEndpoint().(*ClientMessage_Nodeid); ok {
		return x.Nodeid
	}
	return ""
}

func (x *ClientMessage) GetServer() string {
	if x, ok := x.GetEndpoint().(*ClientMessage_Server); ok {
		return x.Server
	}
	return ""
}

type isClientMessage_Endpoint interface {
	isClientMessage_Endpoint()
}

type ClientMessage_Nodeid struct {
	Nodeid string `protobuf:"bytes,5,opt,name=nodeid,proto3,oneof"`
}

type ClientMessage_Server struct {
	Server string `protobuf:"bytes,6,opt,name=server,proto3,oneof"`
}

func (*ClientMessage_Nodeid) isClientMessage_Endpoint() {}

func (*ClientMessage_Server) isClientMessage_Endpoint() {}

type ServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Body    []byte      `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Errcode int32       `protobuf:"varint,3,opt,name=errcode,proto3" json:"errcode,omitempty"`
	Msgtype MessageType `protobuf:"varint,4,opt,name=msgtype,proto3,enum=gateway.MessageType" json:"msgtype,omitempty"`
	Errmsg  string      `protobuf:"bytes,5,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Msgid   int64       `protobuf:"varint,6,opt,name=msgid,proto3" json:"msgid,omitempty"`
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_client_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerMessage) GetErrcode() int32 {
	if x != nil {
		return x.Errcode
	}
	return 0
}

func (x *ServerMessage) GetMsgtype() MessageType {
	if x != nil {
		return x.Msgtype
	}
	return MessageType_Aync
}

func (x *ServerMessage) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *ServerMessage) GetMsgid() int64 {
	if x != nil {
		return x.Msgid
	}
	return 0
}

type CaptchaQuestion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaptchId   string `protobuf:"bytes,1,opt,name=captch_id,json=captchId,proto3" json:"captch_id,omitempty"`
	CaptchType string `protobuf:"bytes,2,opt,name=captch_type,json=captchType,proto3" json:"captch_type,omitempty"`
	CatpchRaw  []byte `protobuf:"bytes,3,opt,name=catpch_raw,json=catpchRaw,proto3" json:"catpch_raw,omitempty"`
}

func (x *CaptchaQuestion) Reset() {
	*x = CaptchaQuestion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptchaQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaQuestion) ProtoMessage() {}

func (x *CaptchaQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaQuestion.ProtoReflect.Descriptor instead.
func (*CaptchaQuestion) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_client_proto_rawDescGZIP(), []int{2}
}

func (x *CaptchaQuestion) GetCaptchId() string {
	if x != nil {
		return x.CaptchId
	}
	return ""
}

func (x *CaptchaQuestion) GetCaptchType() string {
	if x != nil {
		return x.CaptchType
	}
	return ""
}

func (x *CaptchaQuestion) GetCatpchRaw() []byte {
	if x != nil {
		return x.CatpchRaw
	}
	return nil
}

type CaptchaAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaptchId     string `protobuf:"bytes,1,opt,name=captch_id,json=captchId,proto3" json:"captch_id,omitempty"`
	CaptchType   string `protobuf:"bytes,2,opt,name=captch_type,json=captchType,proto3" json:"captch_type,omitempty"`
	CaptchAnswer string `protobuf:"bytes,3,opt,name=captch_answer,json=captchAnswer,proto3" json:"captch_answer,omitempty"`
}

func (x *CaptchaAnswer) Reset() {
	*x = CaptchaAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_client_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptchaAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaAnswer) ProtoMessage() {}

func (x *CaptchaAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_client_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaAnswer.ProtoReflect.Descriptor instead.
func (*CaptchaAnswer) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_client_proto_rawDescGZIP(), []int{3}
}

func (x *CaptchaAnswer) GetCaptchId() string {
	if x != nil {
		return x.CaptchId
	}
	return ""
}

func (x *CaptchaAnswer) GetCaptchType() string {
	if x != nil {
		return x.CaptchType
	}
	return ""
}

func (x *CaptchaAnswer) GetCaptchAnswer() string {
	if x != nil {
		return x.CaptchAnswer
	}
	return ""
}

type AccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string         `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Passwd  string         `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	Answer  *CaptchaAnswer `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_client_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_client_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_client_proto_rawDescGZIP(), []int{4}
}

func (x *AccountInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AccountInfo) GetPasswd() string {
	if x != nil {
		return x.Passwd
	}
	return ""
}

func (x *AccountInfo) GetAnswer() *CaptchaAnswer {
	if x != nil {
		return x.Answer
	}
	return nil
}

type SessionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account   string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Sessionid string `protobuf:"bytes,2,opt,name=sessionid,proto3" json:"sessionid,omitempty"`
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_client_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_client_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_client_proto_rawDescGZIP(), []int{5}
}

func (x *SessionInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SessionInfo) GetSessionid() string {
	if x != nil {
		return x.Sessionid
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Checker:
	//	*LoginRequest_Account
	//	*LoginRequest_Session
	//	*LoginRequest_Jwt
	Checker isLoginRequest_Checker `protobuf_oneof:"checker"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_client_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_client_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_client_proto_rawDescGZIP(), []int{6}
}

func (m *LoginRequest) GetChecker() isLoginRequest_Checker {
	if m != nil {
		return m.Checker
	}
	return nil
}

func (x *LoginRequest) GetAccount() *AccountInfo {
	if x, ok := x.GetChecker().(*LoginRequest_Account); ok {
		return x.Account
	}
	return nil
}

func (x *LoginRequest) GetSession() *SessionInfo {
	if x, ok := x.GetChecker().(*LoginRequest_Session); ok {
		return x.Session
	}
	return nil
}

func (x *LoginRequest) GetJwt() string {
	if x, ok := x.GetChecker().(*LoginRequest_Jwt); ok {
		return x.Jwt
	}
	return ""
}

type isLoginRequest_Checker interface {
	isLoginRequest_Checker()
}

type LoginRequest_Account struct {
	Account *AccountInfo `protobuf:"bytes,1,opt,name=account,proto3,oneof"`
}

type LoginRequest_Session struct {
	Session *SessionInfo `protobuf:"bytes,2,opt,name=session,proto3,oneof"`
}

type LoginRequest_Jwt struct {
	Jwt string `protobuf:"bytes,3,opt,name=jwt,proto3,oneof"`
}

func (*LoginRequest_Account) isLoginRequest_Checker() {}

func (*LoginRequest_Session) isLoginRequest_Checker() {}

func (*LoginRequest_Jwt) isLoginRequest_Checker() {}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag      LoginResponse_Flag `protobuf:"varint,1,opt,name=flag,proto3,enum=gateway.LoginResponse_Flag" json:"flag,omitempty"`
	Sessionid string             `protobuf:"bytes,2,opt,name=sessionid,proto3" json:"sessionid,omitempty"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_client_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_client_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_client_proto_rawDescGZIP(), []int{7}
}

func (x *LoginResponse) GetFlag() LoginResponse_Flag {
	if x != nil {
		return x.Flag
	}
	return LoginResponse_Success
}

func (x *LoginResponse) GetSessionid() string {
	if x != nil {
		return x.Sessionid
	}
	return ""
}

type EchoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_client_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_client_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_client_proto_rawDescGZIP(), []int{8}
}

func (x *EchoRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EchoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_client_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_client_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_client_proto_rawDescGZIP(), []int{9}
}

func (x *EchoResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_service_gateway_proto_client_proto protoreflect.FileDescriptor

var file_service_gateway_proto_client_proto_rawDesc = []byte{
	0x0a, 0x22, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x22, 0xbd, 0x01,
	0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x69, 0x64, 0x12, 0x2e, 0x0a,
	0x07, 0x6d, 0x73, 0x67, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14,
	0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x06, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x06, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x42, 0x0a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0xaf, 0x01,
	0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x2e, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67,
	0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x69, 0x64, 0x22,
	0x6e, 0x0a, 0x0f, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x49, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x70, 0x63, 0x68, 0x5f, 0x72, 0x61, 0x77, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x61, 0x74, 0x70, 0x63, 0x68, 0x52, 0x61, 0x77, 0x22,
	0x72, 0x0a, 0x0d, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x5f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x22, 0x6f, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x43,
	0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x06, 0x61, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x22, 0x45, 0x0a, 0x0b, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x22, 0x91, 0x01, 0x0a, 0x0c,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x30,
	0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x03, 0x6a, 0x77, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x03, 0x6a, 0x77, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x22,
	0x84, 0x01, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1b, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x04, 0x66, 0x6c,
	0x61, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x64,
	0x22, 0x24, 0x0a, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x22, 0x21, 0x0a, 0x0b, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x22, 0x0a, 0x0c, 0x45, 0x63, 0x68,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x32, 0x0a,
	0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04,
	0x41, 0x79, 0x6e, 0x63, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x10,
	0x02, 0x42, 0x1f, 0x5a, 0x1d, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_gateway_proto_client_proto_rawDescOnce sync.Once
	file_service_gateway_proto_client_proto_rawDescData = file_service_gateway_proto_client_proto_rawDesc
)

func file_service_gateway_proto_client_proto_rawDescGZIP() []byte {
	file_service_gateway_proto_client_proto_rawDescOnce.Do(func() {
		file_service_gateway_proto_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_gateway_proto_client_proto_rawDescData)
	})
	return file_service_gateway_proto_client_proto_rawDescData
}

var file_service_gateway_proto_client_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_service_gateway_proto_client_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_service_gateway_proto_client_proto_goTypes = []interface{}{
	(MessageType)(0),        // 0: gateway.MessageType
	(LoginResponse_Flag)(0), // 1: gateway.LoginResponse.Flag
	(*ClientMessage)(nil),   // 2: gateway.ClientMessage
	(*ServerMessage)(nil),   // 3: gateway.ServerMessage
	(*CaptchaQuestion)(nil), // 4: gateway.CaptchaQuestion
	(*CaptchaAnswer)(nil),   // 5: gateway.CaptchaAnswer
	(*AccountInfo)(nil),     // 6: gateway.AccountInfo
	(*SessionInfo)(nil),     // 7: gateway.SessionInfo
	(*LoginRequest)(nil),    // 8: gateway.LoginRequest
	(*LoginResponse)(nil),   // 9: gateway.LoginResponse
	(*EchoRequest)(nil),     // 10: gateway.EchoRequest
	(*EchoResponse)(nil),    // 11: gateway.EchoResponse
}
var file_service_gateway_proto_client_proto_depIdxs = []int32{
	0, // 0: gateway.ClientMessage.msgtype:type_name -> gateway.MessageType
	0, // 1: gateway.ServerMessage.msgtype:type_name -> gateway.MessageType
	5, // 2: gateway.AccountInfo.answer:type_name -> gateway.CaptchaAnswer
	6, // 3: gateway.LoginRequest.account:type_name -> gateway.AccountInfo
	7, // 4: gateway.LoginRequest.session:type_name -> gateway.SessionInfo
	1, // 5: gateway.LoginResponse.flag:type_name -> gateway.LoginResponse.Flag
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_service_gateway_proto_client_proto_init() }
func file_service_gateway_proto_client_proto_init() {
	if File_service_gateway_proto_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_gateway_proto_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptchaQuestion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_client_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptchaAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_client_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_client_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_client_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_client_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_client_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_client_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_service_gateway_proto_client_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ClientMessage_Nodeid)(nil),
		(*ClientMessage_Server)(nil),
	}
	file_service_gateway_proto_client_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*LoginRequest_Account)(nil),
		(*LoginRequest_Session)(nil),
		(*LoginRequest_Jwt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_gateway_proto_client_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_gateway_proto_client_proto_goTypes,
		DependencyIndexes: file_service_gateway_proto_client_proto_depIdxs,
		EnumInfos:         file_service_gateway_proto_client_proto_enumTypes,
		MessageInfos:      file_service_gateway_proto_client_proto_msgTypes,
	}.Build()
	File_service_gateway_proto_client_proto = out.File
	file_service_gateway_proto_client_proto_rawDesc = nil
	file_service_gateway_proto_client_proto_goTypes = nil
	file_service_gateway_proto_client_proto_depIdxs = nil
}
