// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: service/gateway/proto/gateway-client.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_Aync     MessageType = 0
	MessageType_Request  MessageType = 1
	MessageType_Response MessageType = 2
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "Aync",
		1: "Request",
		2: "Response",
	}
	MessageType_value = map[string]int32{
		"Aync":     0,
		"Request":  1,
		"Response": 2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_gateway_proto_gateway_client_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_service_gateway_proto_gateway_client_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_client_proto_rawDescGZIP(), []int{0}
}

type MIMEType int32

const (
	MIMEType_Protobuf MIMEType = 0
)

// Enum value maps for MIMEType.
var (
	MIMEType_name = map[int32]string{
		0: "Protobuf",
	}
	MIMEType_value = map[string]int32{
		"Protobuf": 0,
	}
)

func (x MIMEType) Enum() *MIMEType {
	p := new(MIMEType)
	*p = x
	return p
}

func (x MIMEType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MIMEType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_gateway_proto_gateway_client_proto_enumTypes[1].Descriptor()
}

func (MIMEType) Type() protoreflect.EnumType {
	return &file_service_gateway_proto_gateway_client_proto_enumTypes[1]
}

func (x MIMEType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MIMEType.Descriptor instead.
func (MIMEType) EnumDescriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_client_proto_rawDescGZIP(), []int{1}
}

type LoginGateResponse_Flag int32

const (
	LoginGateResponse_Success     LoginGateResponse_Flag = 0
	LoginGateResponse_UnknowError LoginGateResponse_Flag = 1
)

// Enum value maps for LoginGateResponse_Flag.
var (
	LoginGateResponse_Flag_name = map[int32]string{
		0: "Success",
		1: "UnknowError",
	}
	LoginGateResponse_Flag_value = map[string]int32{
		"Success":     0,
		"UnknowError": 1,
	}
)

func (x LoginGateResponse_Flag) Enum() *LoginGateResponse_Flag {
	p := new(LoginGateResponse_Flag)
	*p = x
	return p
}

func (x LoginGateResponse_Flag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginGateResponse_Flag) Descriptor() protoreflect.EnumDescriptor {
	return file_service_gateway_proto_gateway_client_proto_enumTypes[2].Descriptor()
}

func (LoginGateResponse_Flag) Type() protoreflect.EnumType {
	return &file_service_gateway_proto_gateway_client_proto_enumTypes[2]
}

func (x LoginGateResponse_Flag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginGateResponse_Flag.Descriptor instead.
func (LoginGateResponse_Flag) EnumDescriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_client_proto_rawDescGZIP(), []int{6, 0}
}

type GateMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Body   []byte      `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Mime   MIMEType    `protobuf:"varint,3,opt,name=mime,proto3,enum=gateway.MIMEType" json:"mime,omitempty"`
	Type   MessageType `protobuf:"varint,4,opt,name=type,proto3,enum=gateway.MessageType" json:"type,omitempty"`
	Nodeid string      `protobuf:"bytes,5,opt,name=nodeid,proto3" json:"nodeid,omitempty"`
	Server string      `protobuf:"bytes,6,opt,name=server,proto3" json:"server,omitempty"`
	Msgid  int64       `protobuf:"varint,7,opt,name=msgid,proto3" json:"msgid,omitempty"`
}

func (x *GateMessage) Reset() {
	*x = GateMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_gateway_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateMessage) ProtoMessage() {}

func (x *GateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_gateway_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateMessage.ProtoReflect.Descriptor instead.
func (*GateMessage) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_client_proto_rawDescGZIP(), []int{0}
}

func (x *GateMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GateMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *GateMessage) GetMime() MIMEType {
	if x != nil {
		return x.Mime
	}
	return MIMEType_Protobuf
}

func (x *GateMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_Aync
}

func (x *GateMessage) GetNodeid() string {
	if x != nil {
		return x.Nodeid
	}
	return ""
}

func (x *GateMessage) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *GateMessage) GetMsgid() int64 {
	if x != nil {
		return x.Msgid
	}
	return 0
}

type CaptchaQuestion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaptchId   string `protobuf:"bytes,1,opt,name=captch_id,json=captchId,proto3" json:"captch_id,omitempty"`
	CaptchType string `protobuf:"bytes,2,opt,name=captch_type,json=captchType,proto3" json:"captch_type,omitempty"`
	CatpchRaw  []byte `protobuf:"bytes,3,opt,name=catpch_raw,json=catpchRaw,proto3" json:"catpch_raw,omitempty"`
}

func (x *CaptchaQuestion) Reset() {
	*x = CaptchaQuestion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_gateway_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptchaQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaQuestion) ProtoMessage() {}

func (x *CaptchaQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_gateway_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaQuestion.ProtoReflect.Descriptor instead.
func (*CaptchaQuestion) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_client_proto_rawDescGZIP(), []int{1}
}

func (x *CaptchaQuestion) GetCaptchId() string {
	if x != nil {
		return x.CaptchId
	}
	return ""
}

func (x *CaptchaQuestion) GetCaptchType() string {
	if x != nil {
		return x.CaptchType
	}
	return ""
}

func (x *CaptchaQuestion) GetCatpchRaw() []byte {
	if x != nil {
		return x.CatpchRaw
	}
	return nil
}

type CaptchaAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaptchId     string `protobuf:"bytes,1,opt,name=captch_id,json=captchId,proto3" json:"captch_id,omitempty"`
	CaptchType   string `protobuf:"bytes,2,opt,name=captch_type,json=captchType,proto3" json:"captch_type,omitempty"`
	CaptchAnswer string `protobuf:"bytes,3,opt,name=captch_answer,json=captchAnswer,proto3" json:"captch_answer,omitempty"`
}

func (x *CaptchaAnswer) Reset() {
	*x = CaptchaAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_gateway_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptchaAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaAnswer) ProtoMessage() {}

func (x *CaptchaAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_gateway_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaAnswer.ProtoReflect.Descriptor instead.
func (*CaptchaAnswer) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_client_proto_rawDescGZIP(), []int{2}
}

func (x *CaptchaAnswer) GetCaptchId() string {
	if x != nil {
		return x.CaptchId
	}
	return ""
}

func (x *CaptchaAnswer) GetCaptchType() string {
	if x != nil {
		return x.CaptchType
	}
	return ""
}

func (x *CaptchaAnswer) GetCaptchAnswer() string {
	if x != nil {
		return x.CaptchAnswer
	}
	return ""
}

type AccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string         `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Passwd  string         `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	Answer  *CaptchaAnswer `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_gateway_client_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_gateway_client_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_client_proto_rawDescGZIP(), []int{3}
}

func (x *AccountInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AccountInfo) GetPasswd() string {
	if x != nil {
		return x.Passwd
	}
	return ""
}

func (x *AccountInfo) GetAnswer() *CaptchaAnswer {
	if x != nil {
		return x.Answer
	}
	return nil
}

type SessionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account   string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Sessionid string `protobuf:"bytes,2,opt,name=sessionid,proto3" json:"sessionid,omitempty"`
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_gateway_client_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_gateway_client_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_client_proto_rawDescGZIP(), []int{4}
}

func (x *SessionInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SessionInfo) GetSessionid() string {
	if x != nil {
		return x.Sessionid
	}
	return ""
}

type LoginGateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Checker:
	//	*LoginGateRequest_Account
	//	*LoginGateRequest_Session
	//	*LoginGateRequest_Jwt
	Checker isLoginGateRequest_Checker `protobuf_oneof:"checker"`
}

func (x *LoginGateRequest) Reset() {
	*x = LoginGateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_gateway_client_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginGateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGateRequest) ProtoMessage() {}

func (x *LoginGateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_gateway_client_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginGateRequest.ProtoReflect.Descriptor instead.
func (*LoginGateRequest) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_client_proto_rawDescGZIP(), []int{5}
}

func (m *LoginGateRequest) GetChecker() isLoginGateRequest_Checker {
	if m != nil {
		return m.Checker
	}
	return nil
}

func (x *LoginGateRequest) GetAccount() *AccountInfo {
	if x, ok := x.GetChecker().(*LoginGateRequest_Account); ok {
		return x.Account
	}
	return nil
}

func (x *LoginGateRequest) GetSession() *SessionInfo {
	if x, ok := x.GetChecker().(*LoginGateRequest_Session); ok {
		return x.Session
	}
	return nil
}

func (x *LoginGateRequest) GetJwt() string {
	if x, ok := x.GetChecker().(*LoginGateRequest_Jwt); ok {
		return x.Jwt
	}
	return ""
}

type isLoginGateRequest_Checker interface {
	isLoginGateRequest_Checker()
}

type LoginGateRequest_Account struct {
	Account *AccountInfo `protobuf:"bytes,1,opt,name=account,proto3,oneof"`
}

type LoginGateRequest_Session struct {
	Session *SessionInfo `protobuf:"bytes,2,opt,name=session,proto3,oneof"`
}

type LoginGateRequest_Jwt struct {
	Jwt string `protobuf:"bytes,3,opt,name=jwt,proto3,oneof"`
}

func (*LoginGateRequest_Account) isLoginGateRequest_Checker() {}

func (*LoginGateRequest_Session) isLoginGateRequest_Checker() {}

func (*LoginGateRequest_Jwt) isLoginGateRequest_Checker() {}

type LoginGateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag      LoginGateResponse_Flag `protobuf:"varint,1,opt,name=flag,proto3,enum=gateway.LoginGateResponse_Flag" json:"flag,omitempty"`
	Sessionid string                 `protobuf:"bytes,2,opt,name=sessionid,proto3" json:"sessionid,omitempty"`
}

func (x *LoginGateResponse) Reset() {
	*x = LoginGateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_gateway_client_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginGateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGateResponse) ProtoMessage() {}

func (x *LoginGateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_gateway_client_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginGateResponse.ProtoReflect.Descriptor instead.
func (*LoginGateResponse) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_client_proto_rawDescGZIP(), []int{6}
}

func (x *LoginGateResponse) GetFlag() LoginGateResponse_Flag {
	if x != nil {
		return x.Flag
	}
	return LoginGateResponse_Success
}

func (x *LoginGateResponse) GetSessionid() string {
	if x != nil {
		return x.Sessionid
	}
	return ""
}

type EchoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_gateway_client_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_gateway_client_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_client_proto_rawDescGZIP(), []int{7}
}

func (x *EchoRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EchoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_gateway_client_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_gateway_client_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_client_proto_rawDescGZIP(), []int{8}
}

func (x *EchoResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_service_gateway_proto_gateway_client_proto protoreflect.FileDescriptor

var file_service_gateway_proto_gateway_client_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2d,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x22, 0xcc, 0x01, 0x0a, 0x0b, 0x47, 0x61, 0x74, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x25, 0x0a,
	0x04, 0x6d, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x4d, 0x49, 0x4d, 0x45, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x6d, 0x69, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x73, 0x67, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d,
	0x73, 0x67, 0x69, 0x64, 0x22, 0x6e, 0x0a, 0x0f, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x70, 0x74, 0x63,
	0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x70, 0x74,
	0x63, 0x68, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x70, 0x74, 0x63,
	0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x70, 0x63, 0x68, 0x5f,
	0x72, 0x61, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x61, 0x74, 0x70, 0x63,
	0x68, 0x52, 0x61, 0x77, 0x22, 0x72, 0x0a, 0x0d, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x5f, 0x61, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x70, 0x74,
	0x63, 0x68, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x6f, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x45, 0x0a, 0x0b, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x64,
	0x22, 0x95, 0x01, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x47, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00,
	0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x03, 0x6a, 0x77, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x6a, 0x77, 0x74, 0x42, 0x09, 0x0a,
	0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x22, 0x8c, 0x01, 0x0a, 0x11, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x47, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33,
	0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x47, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x04, 0x66,
	0x6c, 0x61, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x69,
	0x64, 0x22, 0x24, 0x0a, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x22, 0x21, 0x0a, 0x0b, 0x45, 0x63, 0x68, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x22, 0x0a, 0x0c, 0x45, 0x63,
	0x68, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x32,
	0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a,
	0x04, 0x41, 0x79, 0x6e, 0x63, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x10, 0x02, 0x2a, 0x18, 0x0a, 0x08, 0x4d, 0x49, 0x4d, 0x45, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c,
	0x0a, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x10, 0x00, 0x42, 0x17, 0x5a, 0x15,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_gateway_proto_gateway_client_proto_rawDescOnce sync.Once
	file_service_gateway_proto_gateway_client_proto_rawDescData = file_service_gateway_proto_gateway_client_proto_rawDesc
)

func file_service_gateway_proto_gateway_client_proto_rawDescGZIP() []byte {
	file_service_gateway_proto_gateway_client_proto_rawDescOnce.Do(func() {
		file_service_gateway_proto_gateway_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_gateway_proto_gateway_client_proto_rawDescData)
	})
	return file_service_gateway_proto_gateway_client_proto_rawDescData
}

var file_service_gateway_proto_gateway_client_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_service_gateway_proto_gateway_client_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_service_gateway_proto_gateway_client_proto_goTypes = []interface{}{
	(MessageType)(0),            // 0: gateway.MessageType
	(MIMEType)(0),               // 1: gateway.MIMEType
	(LoginGateResponse_Flag)(0), // 2: gateway.LoginGateResponse.Flag
	(*GateMessage)(nil),         // 3: gateway.GateMessage
	(*CaptchaQuestion)(nil),     // 4: gateway.CaptchaQuestion
	(*CaptchaAnswer)(nil),       // 5: gateway.CaptchaAnswer
	(*AccountInfo)(nil),         // 6: gateway.AccountInfo
	(*SessionInfo)(nil),         // 7: gateway.SessionInfo
	(*LoginGateRequest)(nil),    // 8: gateway.LoginGateRequest
	(*LoginGateResponse)(nil),   // 9: gateway.LoginGateResponse
	(*EchoRequest)(nil),         // 10: gateway.EchoRequest
	(*EchoResponse)(nil),        // 11: gateway.EchoResponse
}
var file_service_gateway_proto_gateway_client_proto_depIdxs = []int32{
	1, // 0: gateway.GateMessage.mime:type_name -> gateway.MIMEType
	0, // 1: gateway.GateMessage.type:type_name -> gateway.MessageType
	5, // 2: gateway.AccountInfo.answer:type_name -> gateway.CaptchaAnswer
	6, // 3: gateway.LoginGateRequest.account:type_name -> gateway.AccountInfo
	7, // 4: gateway.LoginGateRequest.session:type_name -> gateway.SessionInfo
	2, // 5: gateway.LoginGateResponse.flag:type_name -> gateway.LoginGateResponse.Flag
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_service_gateway_proto_gateway_client_proto_init() }
func file_service_gateway_proto_gateway_client_proto_init() {
	if File_service_gateway_proto_gateway_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_gateway_proto_gateway_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_gateway_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptchaQuestion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_gateway_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptchaAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_gateway_client_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_gateway_client_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_gateway_client_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginGateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_gateway_client_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginGateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_gateway_client_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_gateway_client_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_service_gateway_proto_gateway_client_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*LoginGateRequest_Account)(nil),
		(*LoginGateRequest_Session)(nil),
		(*LoginGateRequest_Jwt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_gateway_proto_gateway_client_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_gateway_proto_gateway_client_proto_goTypes,
		DependencyIndexes: file_service_gateway_proto_gateway_client_proto_depIdxs,
		EnumInfos:         file_service_gateway_proto_gateway_client_proto_enumTypes,
		MessageInfos:      file_service_gateway_proto_gateway_client_proto_msgTypes,
	}.Build()
	File_service_gateway_proto_gateway_client_proto = out.File
	file_service_gateway_proto_gateway_client_proto_rawDesc = nil
	file_service_gateway_proto_gateway_client_proto_goTypes = nil
	file_service_gateway_proto_gateway_client_proto_depIdxs = nil
}
