// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: service/gateway/proto/gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForwardEndpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Endpoint:
	//	*ForwardEndpoint_Uid
	//	*ForwardEndpoint_Socketid
	Endpoint isForwardEndpoint_Endpoint `protobuf_oneof:"endpoint"`
}

func (x *ForwardEndpoint) Reset() {
	*x = ForwardEndpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardEndpoint) ProtoMessage() {}

func (x *ForwardEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardEndpoint.ProtoReflect.Descriptor instead.
func (*ForwardEndpoint) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (m *ForwardEndpoint) GetEndpoint() isForwardEndpoint_Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

func (x *ForwardEndpoint) GetUid() int64 {
	if x, ok := x.GetEndpoint().(*ForwardEndpoint_Uid); ok {
		return x.Uid
	}
	return 0
}

func (x *ForwardEndpoint) GetSocketid() string {
	if x, ok := x.GetEndpoint().(*ForwardEndpoint_Socketid); ok {
		return x.Socketid
	}
	return ""
}

type isForwardEndpoint_Endpoint interface {
	isForwardEndpoint_Endpoint()
}

type ForwardEndpoint_Uid struct {
	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3,oneof"`
}

type ForwardEndpoint_Socketid struct {
	Socketid string `protobuf:"bytes,2,opt,name=socketid,proto3,oneof"`
}

func (*ForwardEndpoint_Uid) isForwardEndpoint_Endpoint() {}

func (*ForwardEndpoint_Socketid) isForwardEndpoint_Endpoint() {}

type ForwardMessageWarp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src     *ForwardEndpoint `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dest    *ForwardEndpoint `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	MsgName string           `protobuf:"bytes,3,opt,name=msg_name,json=msgName,proto3" json:"msg_name,omitempty"`
	Data    []byte           `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Type    MessageType      `protobuf:"varint,6,opt,name=type,proto3,enum=gateway.MessageType" json:"type,omitempty"`
	Mime    MIMEType         `protobuf:"varint,5,opt,name=mime,proto3,enum=gateway.MIMEType" json:"mime,omitempty"`
}

func (x *ForwardMessageWarp) Reset() {
	*x = ForwardMessageWarp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardMessageWarp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardMessageWarp) ProtoMessage() {}

func (x *ForwardMessageWarp) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardMessageWarp.ProtoReflect.Descriptor instead.
func (*ForwardMessageWarp) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardMessageWarp) GetSrc() *ForwardEndpoint {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *ForwardMessageWarp) GetDest() *ForwardEndpoint {
	if x != nil {
		return x.Dest
	}
	return nil
}

func (x *ForwardMessageWarp) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *ForwardMessageWarp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ForwardMessageWarp) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_Aync
}

func (x *ForwardMessageWarp) GetMime() MIMEType {
	if x != nil {
		return x.Mime
	}
	return MIMEType_Protobuf
}

type ToUserMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data       []byte      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ToUid      int64       `protobuf:"varint,3,opt,name=to_uid,json=toUid,proto3" json:"to_uid,omitempty"`
	ToSocketid string      `protobuf:"bytes,4,opt,name=to_socketid,json=toSocketid,proto3" json:"to_socketid,omitempty"`
	Mime       MIMEType    `protobuf:"varint,5,opt,name=mime,proto3,enum=gateway.MIMEType" json:"mime,omitempty"`
	Type       MessageType `protobuf:"varint,6,opt,name=type,proto3,enum=gateway.MessageType" json:"type,omitempty"`
}

func (x *ToUserMessage) Reset() {
	*x = ToUserMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_gateway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToUserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToUserMessage) ProtoMessage() {}

func (x *ToUserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_gateway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToUserMessage.ProtoReflect.Descriptor instead.
func (*ToUserMessage) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ToUserMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToUserMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ToUserMessage) GetToUid() int64 {
	if x != nil {
		return x.ToUid
	}
	return 0
}

func (x *ToUserMessage) GetToSocketid() string {
	if x != nil {
		return x.ToSocketid
	}
	return ""
}

func (x *ToUserMessage) GetMime() MIMEType {
	if x != nil {
		return x.Mime
	}
	return MIMEType_Protobuf
}

func (x *ToUserMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_Aync
}

type ToServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data         []byte      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	FromUid      int64       `protobuf:"varint,3,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	FromSocketid string      `protobuf:"bytes,4,opt,name=from_socketid,json=fromSocketid,proto3" json:"from_socketid,omitempty"`
	Mime         MIMEType    `protobuf:"varint,5,opt,name=mime,proto3,enum=gateway.MIMEType" json:"mime,omitempty"`
	Type         MessageType `protobuf:"varint,6,opt,name=type,proto3,enum=gateway.MessageType" json:"type,omitempty"`
}

func (x *ToServerMessage) Reset() {
	*x = ToServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_gateway_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToServerMessage) ProtoMessage() {}

func (x *ToServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_gateway_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToServerMessage.ProtoReflect.Descriptor instead.
func (*ToServerMessage) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ToServerMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToServerMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ToServerMessage) GetFromUid() int64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *ToServerMessage) GetFromSocketid() string {
	if x != nil {
		return x.FromSocketid
	}
	return ""
}

func (x *ToServerMessage) GetMime() MIMEType {
	if x != nil {
		return x.Mime
	}
	return MIMEType_Protobuf
}

func (x *ToServerMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_Aync
}

type AddGateAllowListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *AddGateAllowListRequest) Reset() {
	*x = AddGateAllowListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_gateway_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGateAllowListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGateAllowListRequest) ProtoMessage() {}

func (x *AddGateAllowListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_gateway_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGateAllowListRequest.ProtoReflect.Descriptor instead.
func (*AddGateAllowListRequest) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *AddGateAllowListRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type AddGateAllowListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddGateAllowListResponse) Reset() {
	*x = AddGateAllowListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_gateway_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGateAllowListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGateAllowListResponse) ProtoMessage() {}

func (x *AddGateAllowListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_gateway_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGateAllowListResponse.ProtoReflect.Descriptor instead.
func (*AddGateAllowListResponse) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_proto_rawDescGZIP(), []int{5}
}

var File_service_gateway_proto_gateway_proto protoreflect.FileDescriptor

var file_service_gateway_proto_gateway_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x1a, 0x2a,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2d, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x0f, 0x46, 0x6f,
	0x72, 0x77, 0x61, 0x72, 0x64, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x1c, 0x0a, 0x08, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x69, 0x64, 0x42,
	0x0a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0xee, 0x01, 0x0a, 0x12,
	0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x61,
	0x72, 0x70, 0x12, 0x2a, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x2c,
	0x0a, 0x04, 0x64, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x45, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x04, 0x64, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x6d, 0x73, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x73, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x28, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x6d, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x4d, 0x49,
	0x4d, 0x45, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x6d, 0x69, 0x6d, 0x65, 0x22, 0xc0, 0x01, 0x0a,
	0x0d, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x6f, 0x5f, 0x75, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x55, 0x69, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x6f, 0x5f, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x69, 0x64, 0x12, 0x25,
	0x0a, 0x04, 0x6d, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x4d, 0x49, 0x4d, 0x45, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x6d, 0x69, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22,
	0xca, 0x01, 0x0a, 0x0f, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x66,
	0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66,
	0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x73,
	0x6f, 0x63, 0x6b, 0x65, 0x74, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66,
	0x72, 0x6f, 0x6d, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x6d,
	0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x4d, 0x49, 0x4d, 0x45, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x6d, 0x69,
	0x6d, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x14, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2f, 0x0a, 0x17,
	0x41, 0x64, 0x64, 0x47, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x1a, 0x0a,
	0x18, 0x41, 0x64, 0x64, 0x47, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xf0, 0x01, 0x0a, 0x07, 0x47, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x3f, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x16,
	0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x18, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x49, 0x0a, 0x07, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x12, 0x1b, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x46, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x61, 0x72, 0x70, 0x1a, 0x1b,
	0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x61, 0x72, 0x70, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x12, 0x59, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x47, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x6f,
	0x77, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x41, 0x64, 0x64, 0x47, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x17, 0x5a, 0x15,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_gateway_proto_gateway_proto_rawDescOnce sync.Once
	file_service_gateway_proto_gateway_proto_rawDescData = file_service_gateway_proto_gateway_proto_rawDesc
)

func file_service_gateway_proto_gateway_proto_rawDescGZIP() []byte {
	file_service_gateway_proto_gateway_proto_rawDescOnce.Do(func() {
		file_service_gateway_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_gateway_proto_gateway_proto_rawDescData)
	})
	return file_service_gateway_proto_gateway_proto_rawDescData
}

var file_service_gateway_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_service_gateway_proto_gateway_proto_goTypes = []interface{}{
	(*ForwardEndpoint)(nil),          // 0: gateway.ForwardEndpoint
	(*ForwardMessageWarp)(nil),       // 1: gateway.ForwardMessageWarp
	(*ToUserMessage)(nil),            // 2: gateway.ToUserMessage
	(*ToServerMessage)(nil),          // 3: gateway.ToServerMessage
	(*AddGateAllowListRequest)(nil),  // 4: gateway.AddGateAllowListRequest
	(*AddGateAllowListResponse)(nil), // 5: gateway.AddGateAllowListResponse
	(MessageType)(0),                 // 6: gateway.MessageType
	(MIMEType)(0),                    // 7: gateway.MIMEType
}
var file_service_gateway_proto_gateway_proto_depIdxs = []int32{
	0,  // 0: gateway.ForwardMessageWarp.src:type_name -> gateway.ForwardEndpoint
	0,  // 1: gateway.ForwardMessageWarp.dest:type_name -> gateway.ForwardEndpoint
	6,  // 2: gateway.ForwardMessageWarp.type:type_name -> gateway.MessageType
	7,  // 3: gateway.ForwardMessageWarp.mime:type_name -> gateway.MIMEType
	7,  // 4: gateway.ToUserMessage.mime:type_name -> gateway.MIMEType
	6,  // 5: gateway.ToUserMessage.type:type_name -> gateway.MessageType
	7,  // 6: gateway.ToServerMessage.mime:type_name -> gateway.MIMEType
	6,  // 7: gateway.ToServerMessage.type:type_name -> gateway.MessageType
	2,  // 8: gateway.Gateway.Proxy:input_type -> gateway.ToUserMessage
	1,  // 9: gateway.Gateway.Forward:input_type -> gateway.ForwardMessageWarp
	4,  // 10: gateway.Gateway.AddGateAllowList:input_type -> gateway.AddGateAllowListRequest
	3,  // 11: gateway.Gateway.Proxy:output_type -> gateway.ToServerMessage
	1,  // 12: gateway.Gateway.Forward:output_type -> gateway.ForwardMessageWarp
	5,  // 13: gateway.Gateway.AddGateAllowList:output_type -> gateway.AddGateAllowListResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_service_gateway_proto_gateway_proto_init() }
func file_service_gateway_proto_gateway_proto_init() {
	if File_service_gateway_proto_gateway_proto != nil {
		return
	}
	file_service_gateway_proto_gateway_client_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_gateway_proto_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardEndpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardMessageWarp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_gateway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToUserMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_gateway_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_gateway_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGateAllowListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_gateway_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGateAllowListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_service_gateway_proto_gateway_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ForwardEndpoint_Uid)(nil),
		(*ForwardEndpoint_Socketid)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_gateway_proto_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_gateway_proto_gateway_proto_goTypes,
		DependencyIndexes: file_service_gateway_proto_gateway_proto_depIdxs,
		MessageInfos:      file_service_gateway_proto_gateway_proto_msgTypes,
	}.Build()
	File_service_gateway_proto_gateway_proto = out.File
	file_service_gateway_proto_gateway_proto_rawDesc = nil
	file_service_gateway_proto_gateway_proto_goTypes = nil
	file_service_gateway_proto_gateway_proto_depIdxs = nil
}
