// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: service/gateway/proto/gateway.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GatewayClient is the client API for Gateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayClient interface {
	Proxy(ctx context.Context, opts ...grpc.CallOption) (Gateway_ProxyClient, error)
	AddGateAllowList(ctx context.Context, in *AddGateAllowListRequest, opts ...grpc.CallOption) (*AddGateAllowListResponse, error)
}

type gatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayClient(cc grpc.ClientConnInterface) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) Proxy(ctx context.Context, opts ...grpc.CallOption) (Gateway_ProxyClient, error) {
	stream, err := c.cc.NewStream(ctx, &Gateway_ServiceDesc.Streams[0], "/gateway.Gateway/Proxy", opts...)
	if err != nil {
		return nil, err
	}
	x := &gatewayProxyClient{stream}
	return x, nil
}

type Gateway_ProxyClient interface {
	Send(*ToClientMessage) error
	Recv() (*ToServerMessage, error)
	grpc.ClientStream
}

type gatewayProxyClient struct {
	grpc.ClientStream
}

func (x *gatewayProxyClient) Send(m *ToClientMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gatewayProxyClient) Recv() (*ToServerMessage, error) {
	m := new(ToServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gatewayClient) AddGateAllowList(ctx context.Context, in *AddGateAllowListRequest, opts ...grpc.CallOption) (*AddGateAllowListResponse, error) {
	out := new(AddGateAllowListResponse)
	err := c.cc.Invoke(ctx, "/gateway.Gateway/AddGateAllowList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServer is the server API for Gateway service.
// All implementations must embed UnimplementedGatewayServer
// for forward compatibility
type GatewayServer interface {
	Proxy(Gateway_ProxyServer) error
	AddGateAllowList(context.Context, *AddGateAllowListRequest) (*AddGateAllowListResponse, error)
	mustEmbedUnimplementedGatewayServer()
}

// UnimplementedGatewayServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayServer struct {
}

func (UnimplementedGatewayServer) Proxy(Gateway_ProxyServer) error {
	return status.Errorf(codes.Unimplemented, "method Proxy not implemented")
}
func (UnimplementedGatewayServer) AddGateAllowList(context.Context, *AddGateAllowListRequest) (*AddGateAllowListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGateAllowList not implemented")
}
func (UnimplementedGatewayServer) mustEmbedUnimplementedGatewayServer() {}

// UnsafeGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServer will
// result in compilation errors.
type UnsafeGatewayServer interface {
	mustEmbedUnimplementedGatewayServer()
}

func RegisterGatewayServer(s grpc.ServiceRegistrar, srv GatewayServer) {
	s.RegisterService(&Gateway_ServiceDesc, srv)
}

func _Gateway_Proxy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayServer).Proxy(&gatewayProxyServer{stream})
}

type Gateway_ProxyServer interface {
	Send(*ToServerMessage) error
	Recv() (*ToClientMessage, error)
	grpc.ServerStream
}

type gatewayProxyServer struct {
	grpc.ServerStream
}

func (x *gatewayProxyServer) Send(m *ToServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gatewayProxyServer) Recv() (*ToClientMessage, error) {
	m := new(ToClientMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Gateway_AddGateAllowList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGateAllowListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).AddGateAllowList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.Gateway/AddGateAllowList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).AddGateAllowList(ctx, req.(*AddGateAllowListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gateway_ServiceDesc is the grpc.ServiceDesc for Gateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddGateAllowList",
			Handler:    _Gateway_AddGateAllowList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Proxy",
			Handler:       _Gateway_Proxy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service/gateway/proto/gateway.proto",
}
