// Code generated by xormtool (version: 0.5.0).

package models

import (
	"time"
)

type User struct {
	Id          int64     `xorm:"pk autoincr BIGINT(20)"`
	Name        string    `xorm:"not null unique VARCHAR(32)"`
	Salt        string    `xorm:"not null default '' VARCHAR(32)"`
	Passwd      string    `xorm:"not null VARCHAR(64)"`
	Nickname    string    `xorm:"not null default '' VARCHAR(64)"`
	Phone       string    `xorm:"not null default '' VARCHAR(16)"`
	Stat        int       `xorm:"not null default 0 INT(11)"`
	CreateAt    time.Time `xorm:"not null default CURRENT_TIMESTAMP created TIMESTAMP"`
	LastLoginAt time.Time `xorm:"not null default '0000-00-00 00:00:00' TIMESTAMP"`
	LastLoginIp string    `xorm:"not null default '' VARCHAR(255)"`
}
