// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.18.1
// source: proto/battle_client.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerReadyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId   string `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	ReadyState int32  `protobuf:"varint,2,opt,name=ready_state,json=readyState,proto3" json:"ready_state,omitempty"`
}

func (x *PlayerReadyRequest) Reset() {
	*x = PlayerReadyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_battle_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerReadyRequest) ProtoMessage() {}

func (x *PlayerReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerReadyRequest.ProtoReflect.Descriptor instead.
func (*PlayerReadyRequest) Descriptor() ([]byte, []int) {
	return file_proto_battle_client_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerReadyRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *PlayerReadyRequest) GetReadyState() int32 {
	if x != nil {
		return x.ReadyState
	}
	return 0
}

type PlayerReadyResonse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReadyInfo []*PlayerReadyResonse_ReadyInfo `protobuf:"bytes,1,rep,name=ready_info,json=readyInfo,proto3" json:"ready_info,omitempty"`
}

func (x *PlayerReadyResonse) Reset() {
	*x = PlayerReadyResonse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_battle_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerReadyResonse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerReadyResonse) ProtoMessage() {}

func (x *PlayerReadyResonse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerReadyResonse.ProtoReflect.Descriptor instead.
func (*PlayerReadyResonse) Descriptor() ([]byte, []int) {
	return file_proto_battle_client_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerReadyResonse) GetReadyInfo() []*PlayerReadyResonse_ReadyInfo {
	if x != nil {
		return x.ReadyInfo
	}
	return nil
}

type GameMessageWrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId string `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Msgid    int32  `protobuf:"varint,2,opt,name=msgid,proto3" json:"msgid,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GameMessageWrap) Reset() {
	*x = GameMessageWrap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_battle_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameMessageWrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessageWrap) ProtoMessage() {}

func (x *GameMessageWrap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessageWrap.ProtoReflect.Descriptor instead.
func (*GameMessageWrap) Descriptor() ([]byte, []int) {
	return file_proto_battle_client_proto_rawDescGZIP(), []int{2}
}

func (x *GameMessageWrap) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *GameMessageWrap) GetMsgid() int32 {
	if x != nil {
		return x.Msgid
	}
	return 0
}

func (x *GameMessageWrap) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PlayerReadyResonse_ReadyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatId     int32 `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Uid        int64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	ReadyState int32 `protobuf:"varint,3,opt,name=ready_state,json=readyState,proto3" json:"ready_state,omitempty"`
}

func (x *PlayerReadyResonse_ReadyInfo) Reset() {
	*x = PlayerReadyResonse_ReadyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_battle_client_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerReadyResonse_ReadyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerReadyResonse_ReadyInfo) ProtoMessage() {}

func (x *PlayerReadyResonse_ReadyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_client_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerReadyResonse_ReadyInfo.ProtoReflect.Descriptor instead.
func (*PlayerReadyResonse_ReadyInfo) Descriptor() ([]byte, []int) {
	return file_proto_battle_client_proto_rawDescGZIP(), []int{1, 0}
}

func (x *PlayerReadyResonse_ReadyInfo) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *PlayerReadyResonse_ReadyInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerReadyResonse_ReadyInfo) GetReadyState() int32 {
	if x != nil {
		return x.ReadyState
	}
	return 0
}

var File_proto_battle_client_proto protoreflect.FileDescriptor

var file_proto_battle_client_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x22, 0x52, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x61,
	0x64, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x61, 0x64, 0x79, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x61,
	0x64, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0xb2, 0x01, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x73, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43,
	0x0a, 0x0a, 0x72, 0x65, 0x61, 0x64, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x73, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x72, 0x65, 0x61, 0x64, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x1a, 0x57, 0x0a, 0x09, 0x52, 0x65, 0x61, 0x64, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72,
	0x65, 0x61, 0x64, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x72, 0x65, 0x61, 0x64, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x58, 0x0a, 0x0f,
	0x47, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x72, 0x61, 0x70, 0x12,
	0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x73, 0x67, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x73, 0x67,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_battle_client_proto_rawDescOnce sync.Once
	file_proto_battle_client_proto_rawDescData = file_proto_battle_client_proto_rawDesc
)

func file_proto_battle_client_proto_rawDescGZIP() []byte {
	file_proto_battle_client_proto_rawDescOnce.Do(func() {
		file_proto_battle_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_battle_client_proto_rawDescData)
	})
	return file_proto_battle_client_proto_rawDescData
}

var file_proto_battle_client_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_battle_client_proto_goTypes = []interface{}{
	(*PlayerReadyRequest)(nil),           // 0: battle.PlayerReadyRequest
	(*PlayerReadyResonse)(nil),           // 1: battle.PlayerReadyResonse
	(*GameMessageWrap)(nil),              // 2: battle.GameMessageWrap
	(*PlayerReadyResonse_ReadyInfo)(nil), // 3: battle.PlayerReadyResonse.ReadyInfo
}
var file_proto_battle_client_proto_depIdxs = []int32{
	3, // 0: battle.PlayerReadyResonse.ready_info:type_name -> battle.PlayerReadyResonse.ReadyInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_battle_client_proto_init() }
func file_proto_battle_client_proto_init() {
	if File_proto_battle_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_battle_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerReadyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_battle_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerReadyResonse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_battle_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameMessageWrap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_battle_client_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerReadyResonse_ReadyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_battle_client_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_battle_client_proto_goTypes,
		DependencyIndexes: file_proto_battle_client_proto_depIdxs,
		MessageInfos:      file_proto_battle_client_proto_msgTypes,
	}.Build()
	File_proto_battle_client_proto = out.File
	file_proto_battle_client_proto_rawDesc = nil
	file_proto_battle_client_proto_goTypes = nil
	file_proto_battle_client_proto_depIdxs = nil
}
