// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: service/battle/proto/battle_server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BattleOverReport_State int32

const (
	BattleOverReport_Finished  BattleOverReport_State = 0 // 完成
	BattleOverReport_Disbanded BattleOverReport_State = 1 // 解散
	BattleOverReport_Timeover  BattleOverReport_State = 2 // 超时
)

// Enum value maps for BattleOverReport_State.
var (
	BattleOverReport_State_name = map[int32]string{
		0: "Finished",
		1: "Disbanded",
		2: "Timeover",
	}
	BattleOverReport_State_value = map[string]int32{
		"Finished":  0,
		"Disbanded": 1,
		"Timeover":  2,
	}
)

func (x BattleOverReport_State) Enum() *BattleOverReport_State {
	p := new(BattleOverReport_State)
	*p = x
	return p
}

func (x BattleOverReport_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleOverReport_State) Descriptor() protoreflect.EnumDescriptor {
	return file_service_battle_proto_battle_server_proto_enumTypes[0].Descriptor()
}

func (BattleOverReport_State) Type() protoreflect.EnumType {
	return &file_service_battle_proto_battle_server_proto_enumTypes[0]
}

func (x BattleOverReport_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleOverReport_State.Descriptor instead.
func (BattleOverReport_State) EnumDescriptor() ([]byte, []int) {
	return file_service_battle_proto_battle_server_proto_rawDescGZIP(), []int{10, 0}
}

type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	SeatId  int32 `protobuf:"varint,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Score   int64 `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	IsRobot bool  `protobuf:"varint,4,opt,name=is_robot,json=isRobot,proto3" json:"is_robot,omitempty"`
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_battle_proto_battle_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_battle_proto_battle_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_service_battle_proto_battle_server_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerInfo) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *PlayerInfo) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PlayerInfo) GetIsRobot() bool {
	if x != nil {
		return x.IsRobot
	}
	return false
}

type BattleConfigure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxGameTime int32 `protobuf:"varint,1,opt,name=max_game_time,json=maxGameTime,proto3" json:"max_game_time,omitempty"` // 游戏最大进行时间, 单位: second
	// Types that are assignable to StartCondition:
	//	*BattleConfigure_Delayed
	//	*BattleConfigure_ByControl
	StartCondition isBattleConfigure_StartCondition `protobuf_oneof:"start_condition"`
}

func (x *BattleConfigure) Reset() {
	*x = BattleConfigure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_battle_proto_battle_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleConfigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleConfigure) ProtoMessage() {}

func (x *BattleConfigure) ProtoReflect() protoreflect.Message {
	mi := &file_service_battle_proto_battle_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleConfigure.ProtoReflect.Descriptor instead.
func (*BattleConfigure) Descriptor() ([]byte, []int) {
	return file_service_battle_proto_battle_server_proto_rawDescGZIP(), []int{1}
}

func (x *BattleConfigure) GetMaxGameTime() int32 {
	if x != nil {
		return x.MaxGameTime
	}
	return 0
}

func (m *BattleConfigure) GetStartCondition() isBattleConfigure_StartCondition {
	if m != nil {
		return m.StartCondition
	}
	return nil
}

func (x *BattleConfigure) GetDelayed() int32 {
	if x, ok := x.GetStartCondition().(*BattleConfigure_Delayed); ok {
		return x.Delayed
	}
	return 0
}

func (x *BattleConfigure) GetByControl() bool {
	if x, ok := x.GetStartCondition().(*BattleConfigure_ByControl); ok {
		return x.ByControl
	}
	return false
}

type isBattleConfigure_StartCondition interface {
	isBattleConfigure_StartCondition()
}

type BattleConfigure_Delayed struct {
	Delayed int32 `protobuf:"varint,2,opt,name=delayed,proto3,oneof"`
}

type BattleConfigure_ByControl struct {
	ByControl bool `protobuf:"varint,3,opt,name=by_control,json=byControl,proto3,oneof"`
}

func (*BattleConfigure_Delayed) isBattleConfigure_StartCondition() {}

func (*BattleConfigure_ByControl) isBattleConfigure_StartCondition() {}

type CreateBattleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameName    string           `protobuf:"bytes,1,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	GameConf    []byte           `protobuf:"bytes,2,opt,name=game_conf,json=gameConf,proto3" json:"game_conf,omitempty"`
	BattleConf  *BattleConfigure `protobuf:"bytes,3,opt,name=battle_conf,json=battleConf,proto3" json:"battle_conf,omitempty"`
	PlayerInfos []*PlayerInfo    `protobuf:"bytes,4,rep,name=player_infos,json=playerInfos,proto3" json:"player_infos,omitempty"`
}

func (x *CreateBattleRequest) Reset() {
	*x = CreateBattleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_battle_proto_battle_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBattleRequest) ProtoMessage() {}

func (x *CreateBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_battle_proto_battle_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBattleRequest.ProtoReflect.Descriptor instead.
func (*CreateBattleRequest) Descriptor() ([]byte, []int) {
	return file_service_battle_proto_battle_server_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBattleRequest) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *CreateBattleRequest) GetGameConf() []byte {
	if x != nil {
		return x.GameConf
	}
	return nil
}

func (x *CreateBattleRequest) GetBattleConf() *BattleConfigure {
	if x != nil {
		return x.BattleConf
	}
	return nil
}

func (x *CreateBattleRequest) GetPlayerInfos() []*PlayerInfo {
	if x != nil {
		return x.PlayerInfos
	}
	return nil
}

type CreateBattleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId string `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	NodeId   string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
}

func (x *CreateBattleResponse) Reset() {
	*x = CreateBattleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_battle_proto_battle_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBattleResponse) ProtoMessage() {}

func (x *CreateBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_battle_proto_battle_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBattleResponse.ProtoReflect.Descriptor instead.
func (*CreateBattleResponse) Descriptor() ([]byte, []int) {
	return file_service_battle_proto_battle_server_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBattleResponse) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *CreateBattleResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type StartBattleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId string `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
}

func (x *StartBattleRequest) Reset() {
	*x = StartBattleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_battle_proto_battle_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBattleRequest) ProtoMessage() {}

func (x *StartBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_battle_proto_battle_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBattleRequest.ProtoReflect.Descriptor instead.
func (*StartBattleRequest) Descriptor() ([]byte, []int) {
	return file_service_battle_proto_battle_server_proto_rawDescGZIP(), []int{4}
}

func (x *StartBattleRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

type StartBattleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartBattleResponse) Reset() {
	*x = StartBattleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_battle_proto_battle_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBattleResponse) ProtoMessage() {}

func (x *StartBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_battle_proto_battle_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBattleResponse.ProtoReflect.Descriptor instead.
func (*StartBattleResponse) Descriptor() ([]byte, []int) {
	return file_service_battle_proto_battle_server_proto_rawDescGZIP(), []int{5}
}

type StopBattleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId string `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
}

func (x *StopBattleRequest) Reset() {
	*x = StopBattleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_battle_proto_battle_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopBattleRequest) ProtoMessage() {}

func (x *StopBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_battle_proto_battle_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopBattleRequest.ProtoReflect.Descriptor instead.
func (*StopBattleRequest) Descriptor() ([]byte, []int) {
	return file_service_battle_proto_battle_server_proto_rawDescGZIP(), []int{6}
}

func (x *StopBattleRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

type StopBattleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopBattleResponse) Reset() {
	*x = StopBattleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_battle_proto_battle_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopBattleResponse) ProtoMessage() {}

func (x *StopBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_battle_proto_battle_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopBattleResponse.ProtoReflect.Descriptor instead.
func (*StopBattleResponse) Descriptor() ([]byte, []int) {
	return file_service_battle_proto_battle_server_proto_rawDescGZIP(), []int{7}
}

type WatcherJoinBattleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId    string        `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	PlayerInfos []*PlayerInfo `protobuf:"bytes,4,rep,name=player_infos,json=playerInfos,proto3" json:"player_infos,omitempty"`
}

func (x *WatcherJoinBattleRequest) Reset() {
	*x = WatcherJoinBattleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_battle_proto_battle_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatcherJoinBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatcherJoinBattleRequest) ProtoMessage() {}

func (x *WatcherJoinBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_battle_proto_battle_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatcherJoinBattleRequest.ProtoReflect.Descriptor instead.
func (*WatcherJoinBattleRequest) Descriptor() ([]byte, []int) {
	return file_service_battle_proto_battle_server_proto_rawDescGZIP(), []int{8}
}

func (x *WatcherJoinBattleRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *WatcherJoinBattleRequest) GetPlayerInfos() []*PlayerInfo {
	if x != nil {
		return x.PlayerInfos
	}
	return nil
}

type WatcherJoinBattleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WatcherJoinBattleResponse) Reset() {
	*x = WatcherJoinBattleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_battle_proto_battle_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatcherJoinBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatcherJoinBattleResponse) ProtoMessage() {}

func (x *WatcherJoinBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_battle_proto_battle_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatcherJoinBattleResponse.ProtoReflect.Descriptor instead.
func (*WatcherJoinBattleResponse) Descriptor() ([]byte, []int) {
	return file_service_battle_proto_battle_server_proto_rawDescGZIP(), []int{9}
}

type BattleOverReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State BattleOverReport_State                  `protobuf:"varint,1,opt,name=state,proto3,enum=battle.BattleOverReport_State" json:"state,omitempty"`
	Tally map[int32]*BattleOverReport_BattleScore `protobuf:"bytes,2,rep,name=tally,proto3" json:"tally,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *BattleOverReport) Reset() {
	*x = BattleOverReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_battle_proto_battle_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleOverReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleOverReport) ProtoMessage() {}

func (x *BattleOverReport) ProtoReflect() protoreflect.Message {
	mi := &file_service_battle_proto_battle_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleOverReport.ProtoReflect.Descriptor instead.
func (*BattleOverReport) Descriptor() ([]byte, []int) {
	return file_service_battle_proto_battle_server_proto_rawDescGZIP(), []int{10}
}

func (x *BattleOverReport) GetState() BattleOverReport_State {
	if x != nil {
		return x.State
	}
	return BattleOverReport_Finished
}

func (x *BattleOverReport) GetTally() map[int32]*BattleOverReport_BattleScore {
	if x != nil {
		return x.Tally
	}
	return nil
}

type BattleMessageWrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId string `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Uid      int64  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Topic    string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Data     []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BattleMessageWrap) Reset() {
	*x = BattleMessageWrap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_battle_proto_battle_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleMessageWrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleMessageWrap) ProtoMessage() {}

func (x *BattleMessageWrap) ProtoReflect() protoreflect.Message {
	mi := &file_service_battle_proto_battle_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleMessageWrap.ProtoReflect.Descriptor instead.
func (*BattleMessageWrap) Descriptor() ([]byte, []int) {
	return file_service_battle_proto_battle_server_proto_rawDescGZIP(), []int{11}
}

func (x *BattleMessageWrap) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *BattleMessageWrap) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BattleMessageWrap) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *BattleMessageWrap) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BattleStartEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BattleStartEvent) Reset() {
	*x = BattleStartEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_battle_proto_battle_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleStartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleStartEvent) ProtoMessage() {}

func (x *BattleStartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_service_battle_proto_battle_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleStartEvent.ProtoReflect.Descriptor instead.
func (*BattleStartEvent) Descriptor() ([]byte, []int) {
	return file_service_battle_proto_battle_server_proto_rawDescGZIP(), []int{12}
}

type BattleOverEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BattleOverEvent) Reset() {
	*x = BattleOverEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_battle_proto_battle_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleOverEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleOverEvent) ProtoMessage() {}

func (x *BattleOverEvent) ProtoReflect() protoreflect.Message {
	mi := &file_service_battle_proto_battle_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleOverEvent.ProtoReflect.Descriptor instead.
func (*BattleOverEvent) Descriptor() ([]byte, []int) {
	return file_service_battle_proto_battle_server_proto_rawDescGZIP(), []int{13}
}

type BattleOverReport_BattleScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score int64             `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Extra map[string]string `protobuf:"bytes,2,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *BattleOverReport_BattleScore) Reset() {
	*x = BattleOverReport_BattleScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_battle_proto_battle_server_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleOverReport_BattleScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleOverReport_BattleScore) ProtoMessage() {}

func (x *BattleOverReport_BattleScore) ProtoReflect() protoreflect.Message {
	mi := &file_service_battle_proto_battle_server_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleOverReport_BattleScore.ProtoReflect.Descriptor instead.
func (*BattleOverReport_BattleScore) Descriptor() ([]byte, []int) {
	return file_service_battle_proto_battle_server_proto_rawDescGZIP(), []int{10, 0}
}

func (x *BattleOverReport_BattleScore) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *BattleOverReport_BattleScore) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

var File_service_battle_proto_battle_server_proto protoreflect.FileDescriptor

var file_service_battle_proto_battle_server_proto_rawDesc = []byte{
	0x0a, 0x28, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x22, 0x68, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x22, 0x85, 0x01, 0x0a,
	0x0f, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65,
	0x12, 0x22, 0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x47, 0x61, 0x6d, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x65, 0x64,
	0x12, 0x1f, 0x0a, 0x0a, 0x62, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x42, 0x11, 0x0a, 0x0f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc0, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x67, 0x61,
	0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x38, 0x0a, 0x0b, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x65, 0x52, 0x0a, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x12, 0x35, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x4c, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x30, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x70, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49,
	0x64, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x70, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6e, 0x0a, 0x18, 0x57, 0x61, 0x74, 0x63, 0x68,
	0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x35, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x1b, 0x0a, 0x19, 0x57, 0x61, 0x74, 0x63, 0x68,
	0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0xbe, 0x03, 0x0a, 0x10, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x4f,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x34, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x39, 0x0a, 0x05, 0x74, 0x61, 0x6c, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x4f, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x54, 0x61, 0x6c, 0x6c, 0x79, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x05, 0x74, 0x61, 0x6c, 0x6c, 0x79, 0x1a, 0xa4, 0x01, 0x0a, 0x0b, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x12, 0x45, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2f, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x4f,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x1a, 0x38, 0x0a, 0x0a, 0x45, 0x78, 0x74, 0x72, 0x61,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x1a, 0x5e, 0x0a, 0x0a, 0x54, 0x61, 0x6c, 0x6c, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x3a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x4f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x32, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x69, 0x73, 0x62,
	0x61, 0x6e, 0x64, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x6f,
	0x76, 0x65, 0x72, 0x10, 0x02, 0x22, 0x6c, 0x0a, 0x11, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x72, 0x61, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x12, 0x0a, 0x10, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x42, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x4f, 0x76, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x32, 0xc2, 0x02, 0x0a, 0x06, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x48, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x12, 0x1a, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0a,
	0x53, 0x74, 0x6f, 0x70, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x19, 0x2e, 0x62, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x53,
	0x74, 0x6f, 0x70, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x11, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x4a, 0x6f,
	0x69, 0x6e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x62, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x16, 0x5a, 0x14, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_battle_proto_battle_server_proto_rawDescOnce sync.Once
	file_service_battle_proto_battle_server_proto_rawDescData = file_service_battle_proto_battle_server_proto_rawDesc
)

func file_service_battle_proto_battle_server_proto_rawDescGZIP() []byte {
	file_service_battle_proto_battle_server_proto_rawDescOnce.Do(func() {
		file_service_battle_proto_battle_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_battle_proto_battle_server_proto_rawDescData)
	})
	return file_service_battle_proto_battle_server_proto_rawDescData
}

var file_service_battle_proto_battle_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_battle_proto_battle_server_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_service_battle_proto_battle_server_proto_goTypes = []interface{}{
	(BattleOverReport_State)(0),          // 0: battle.BattleOverReport.State
	(*PlayerInfo)(nil),                   // 1: battle.PlayerInfo
	(*BattleConfigure)(nil),              // 2: battle.BattleConfigure
	(*CreateBattleRequest)(nil),          // 3: battle.CreateBattleRequest
	(*CreateBattleResponse)(nil),         // 4: battle.CreateBattleResponse
	(*StartBattleRequest)(nil),           // 5: battle.StartBattleRequest
	(*StartBattleResponse)(nil),          // 6: battle.StartBattleResponse
	(*StopBattleRequest)(nil),            // 7: battle.StopBattleRequest
	(*StopBattleResponse)(nil),           // 8: battle.StopBattleResponse
	(*WatcherJoinBattleRequest)(nil),     // 9: battle.WatcherJoinBattleRequest
	(*WatcherJoinBattleResponse)(nil),    // 10: battle.WatcherJoinBattleResponse
	(*BattleOverReport)(nil),             // 11: battle.BattleOverReport
	(*BattleMessageWrap)(nil),            // 12: battle.BattleMessageWrap
	(*BattleStartEvent)(nil),             // 13: battle.BattleStartEvent
	(*BattleOverEvent)(nil),              // 14: battle.BattleOverEvent
	(*BattleOverReport_BattleScore)(nil), // 15: battle.BattleOverReport.BattleScore
	nil,                                  // 16: battle.BattleOverReport.TallyEntry
	nil,                                  // 17: battle.BattleOverReport.BattleScore.ExtraEntry
}
var file_service_battle_proto_battle_server_proto_depIdxs = []int32{
	2,  // 0: battle.CreateBattleRequest.battle_conf:type_name -> battle.BattleConfigure
	1,  // 1: battle.CreateBattleRequest.player_infos:type_name -> battle.PlayerInfo
	1,  // 2: battle.WatcherJoinBattleRequest.player_infos:type_name -> battle.PlayerInfo
	0,  // 3: battle.BattleOverReport.state:type_name -> battle.BattleOverReport.State
	16, // 4: battle.BattleOverReport.tally:type_name -> battle.BattleOverReport.TallyEntry
	17, // 5: battle.BattleOverReport.BattleScore.extra:type_name -> battle.BattleOverReport.BattleScore.ExtraEntry
	15, // 6: battle.BattleOverReport.TallyEntry.value:type_name -> battle.BattleOverReport.BattleScore
	3,  // 7: battle.Battle.CreateBattle:input_type -> battle.CreateBattleRequest
	5,  // 8: battle.Battle.StartBattle:input_type -> battle.StartBattleRequest
	7,  // 9: battle.Battle.StopBattle:input_type -> battle.StopBattleRequest
	9,  // 10: battle.Battle.WatcherJoinBattle:input_type -> battle.WatcherJoinBattleRequest
	4,  // 11: battle.Battle.CreateBattle:output_type -> battle.CreateBattleResponse
	6,  // 12: battle.Battle.StartBattle:output_type -> battle.StartBattleResponse
	8,  // 13: battle.Battle.StopBattle:output_type -> battle.StopBattleResponse
	10, // 14: battle.Battle.WatcherJoinBattle:output_type -> battle.WatcherJoinBattleResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_service_battle_proto_battle_server_proto_init() }
func file_service_battle_proto_battle_server_proto_init() {
	if File_service_battle_proto_battle_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_battle_proto_battle_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_battle_proto_battle_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleConfigure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_battle_proto_battle_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBattleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_battle_proto_battle_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBattleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_battle_proto_battle_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartBattleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_battle_proto_battle_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartBattleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_battle_proto_battle_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopBattleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_battle_proto_battle_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopBattleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_battle_proto_battle_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatcherJoinBattleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_battle_proto_battle_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatcherJoinBattleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_battle_proto_battle_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleOverReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_battle_proto_battle_server_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleMessageWrap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_battle_proto_battle_server_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleStartEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_battle_proto_battle_server_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleOverEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_battle_proto_battle_server_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleOverReport_BattleScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_service_battle_proto_battle_server_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*BattleConfigure_Delayed)(nil),
		(*BattleConfigure_ByControl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_battle_proto_battle_server_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_battle_proto_battle_server_proto_goTypes,
		DependencyIndexes: file_service_battle_proto_battle_server_proto_depIdxs,
		EnumInfos:         file_service_battle_proto_battle_server_proto_enumTypes,
		MessageInfos:      file_service_battle_proto_battle_server_proto_msgTypes,
	}.Build()
	File_service_battle_proto_battle_server_proto = out.File
	file_service_battle_proto_battle_server_proto_rawDesc = nil
	file_service_battle_proto_battle_server_proto_goTypes = nil
	file_service_battle_proto_battle_server_proto_depIdxs = nil
}
