// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.18.1
// source: services/gate/proto/gate.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AsyncMessageWrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta map[string]string `protobuf:"bytes,2,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body []byte            `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// for special server, here is nodeid
	Method  string `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Nodeid  string `protobuf:"bytes,5,opt,name=nodeid,proto3" json:"nodeid,omitempty"`
	Service string `protobuf:"bytes,6,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *AsyncMessageWrap) Reset() {
	*x = AsyncMessageWrap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_gate_proto_gate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AsyncMessageWrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncMessageWrap) ProtoMessage() {}

func (x *AsyncMessageWrap) ProtoReflect() protoreflect.Message {
	mi := &file_services_gate_proto_gate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncMessageWrap.ProtoReflect.Descriptor instead.
func (*AsyncMessageWrap) Descriptor() ([]byte, []int) {
	return file_services_gate_proto_gate_proto_rawDescGZIP(), []int{0}
}

func (x *AsyncMessageWrap) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AsyncMessageWrap) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AsyncMessageWrap) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AsyncMessageWrap) GetNodeid() string {
	if x != nil {
		return x.Nodeid
	}
	return ""
}

func (x *AsyncMessageWrap) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

var File_services_gate_proto_gate_proto protoreflect.FileDescriptor

var file_services_gate_proto_gate_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x67, 0x61, 0x74, 0x65, 0x22, 0xdf, 0x01, 0x0a, 0x10, 0x41, 0x73, 0x79, 0x6e, 0x63,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x72, 0x61, 0x70, 0x12, 0x34, 0x0a, 0x04, 0x6d,
	0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x2e, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x72, 0x61,
	0x70, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x6d, 0x65, 0x74,
	0x61, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e,
	0x6f, 0x64, 0x65, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a,
	0x37, 0x0a, 0x09, 0x4d, 0x65, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x1b, 0x5a, 0x19, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_gate_proto_gate_proto_rawDescOnce sync.Once
	file_services_gate_proto_gate_proto_rawDescData = file_services_gate_proto_gate_proto_rawDesc
)

func file_services_gate_proto_gate_proto_rawDescGZIP() []byte {
	file_services_gate_proto_gate_proto_rawDescOnce.Do(func() {
		file_services_gate_proto_gate_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_gate_proto_gate_proto_rawDescData)
	})
	return file_services_gate_proto_gate_proto_rawDescData
}

var file_services_gate_proto_gate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_gate_proto_gate_proto_goTypes = []interface{}{
	(*AsyncMessageWrap)(nil), // 0: gate.AsyncMessageWrap
	nil,                      // 1: gate.AsyncMessageWrap.MetaEntry
}
var file_services_gate_proto_gate_proto_depIdxs = []int32{
	1, // 0: gate.AsyncMessageWrap.meta:type_name -> gate.AsyncMessageWrap.MetaEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_gate_proto_gate_proto_init() }
func file_services_gate_proto_gate_proto_init() {
	if File_services_gate_proto_gate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_gate_proto_gate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AsyncMessageWrap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_gate_proto_gate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_gate_proto_gate_proto_goTypes,
		DependencyIndexes: file_services_gate_proto_gate_proto_depIdxs,
		MessageInfos:      file_services_gate_proto_gate_proto_msgTypes,
	}.Build()
	File_services_gate_proto_gate_proto = out.File
	file_services_gate_proto_gate_proto_rawDesc = nil
	file_services_gate_proto_gate_proto_goTypes = nil
	file_services_gate_proto_gate_proto_depIdxs = nil
}
