// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.18.1
// source: proto/route.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest_MSGID int32

const (
	LoginRequest_INVALID_MSGID LoginRequest_MSGID = 0
	LoginRequest_ID            LoginRequest_MSGID = 100
)

// Enum value maps for LoginRequest_MSGID.
var (
	LoginRequest_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		100: "ID",
	}
	LoginRequest_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            100,
	}
)

func (x LoginRequest_MSGID) Enum() *LoginRequest_MSGID {
	p := new(LoginRequest_MSGID)
	*p = x
	return p
}

func (x LoginRequest_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginRequest_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_route_proto_enumTypes[0].Descriptor()
}

func (LoginRequest_MSGID) Type() protoreflect.EnumType {
	return &file_proto_route_proto_enumTypes[0]
}

func (x LoginRequest_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginRequest_MSGID.Descriptor instead.
func (LoginRequest_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{1, 0}
}

type LoginResponse_MSGID int32

const (
	LoginResponse_INVALID_MSGID LoginResponse_MSGID = 0
	LoginResponse_ID            LoginResponse_MSGID = 101
)

// Enum value maps for LoginResponse_MSGID.
var (
	LoginResponse_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		101: "ID",
	}
	LoginResponse_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            101,
	}
)

func (x LoginResponse_MSGID) Enum() *LoginResponse_MSGID {
	p := new(LoginResponse_MSGID)
	*p = x
	return p
}

func (x LoginResponse_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginResponse_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_route_proto_enumTypes[1].Descriptor()
}

func (LoginResponse_MSGID) Type() protoreflect.EnumType {
	return &file_proto_route_proto_enumTypes[1]
}

func (x LoginResponse_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginResponse_MSGID.Descriptor instead.
func (LoginResponse_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{2, 0}
}

type LoginResponse_ErrCode int32

const (
	LoginResponse_ok            LoginResponse_ErrCode = 0
	LoginResponse_unkown_err    LoginResponse_ErrCode = 1
	LoginResponse_invalid_token LoginResponse_ErrCode = 11
)

// Enum value maps for LoginResponse_ErrCode.
var (
	LoginResponse_ErrCode_name = map[int32]string{
		0:  "ok",
		1:  "unkown_err",
		11: "invalid_token",
	}
	LoginResponse_ErrCode_value = map[string]int32{
		"ok":            0,
		"unkown_err":    1,
		"invalid_token": 11,
	}
)

func (x LoginResponse_ErrCode) Enum() *LoginResponse_ErrCode {
	p := new(LoginResponse_ErrCode)
	*p = x
	return p
}

func (x LoginResponse_ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginResponse_ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_route_proto_enumTypes[2].Descriptor()
}

func (LoginResponse_ErrCode) Type() protoreflect.EnumType {
	return &file_proto_route_proto_enumTypes[2]
}

func (x LoginResponse_ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginResponse_ErrCode.Descriptor instead.
func (LoginResponse_ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{2, 1}
}

type AccountLoginRequest_MSGID int32

const (
	AccountLoginRequest_INVALID_MSGID AccountLoginRequest_MSGID = 0
	AccountLoginRequest_ID            AccountLoginRequest_MSGID = 102
)

// Enum value maps for AccountLoginRequest_MSGID.
var (
	AccountLoginRequest_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		102: "ID",
	}
	AccountLoginRequest_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            102,
	}
)

func (x AccountLoginRequest_MSGID) Enum() *AccountLoginRequest_MSGID {
	p := new(AccountLoginRequest_MSGID)
	*p = x
	return p
}

func (x AccountLoginRequest_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountLoginRequest_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_route_proto_enumTypes[3].Descriptor()
}

func (AccountLoginRequest_MSGID) Type() protoreflect.EnumType {
	return &file_proto_route_proto_enumTypes[3]
}

func (x AccountLoginRequest_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountLoginRequest_MSGID.Descriptor instead.
func (AccountLoginRequest_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{3, 0}
}

type AccountLoginResponse_MSGID int32

const (
	AccountLoginResponse_INVALID_MSGID AccountLoginResponse_MSGID = 0
	AccountLoginResponse_ID            AccountLoginResponse_MSGID = 103
)

// Enum value maps for AccountLoginResponse_MSGID.
var (
	AccountLoginResponse_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		103: "ID",
	}
	AccountLoginResponse_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            103,
	}
)

func (x AccountLoginResponse_MSGID) Enum() *AccountLoginResponse_MSGID {
	p := new(AccountLoginResponse_MSGID)
	*p = x
	return p
}

func (x AccountLoginResponse_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountLoginResponse_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_route_proto_enumTypes[4].Descriptor()
}

func (AccountLoginResponse_MSGID) Type() protoreflect.EnumType {
	return &file_proto_route_proto_enumTypes[4]
}

func (x AccountLoginResponse_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountLoginResponse_MSGID.Descriptor instead.
func (AccountLoginResponse_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{4, 0}
}

type AccountLoginResponse_ErrCode int32

const (
	AccountLoginResponse_ok            AccountLoginResponse_ErrCode = 0
	AccountLoginResponse_unkown_err    AccountLoginResponse_ErrCode = 1
	AccountLoginResponse_invalid_token AccountLoginResponse_ErrCode = 11
)

// Enum value maps for AccountLoginResponse_ErrCode.
var (
	AccountLoginResponse_ErrCode_name = map[int32]string{
		0:  "ok",
		1:  "unkown_err",
		11: "invalid_token",
	}
	AccountLoginResponse_ErrCode_value = map[string]int32{
		"ok":            0,
		"unkown_err":    1,
		"invalid_token": 11,
	}
)

func (x AccountLoginResponse_ErrCode) Enum() *AccountLoginResponse_ErrCode {
	p := new(AccountLoginResponse_ErrCode)
	*p = x
	return p
}

func (x AccountLoginResponse_ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountLoginResponse_ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_route_proto_enumTypes[5].Descriptor()
}

func (AccountLoginResponse_ErrCode) Type() protoreflect.EnumType {
	return &file_proto_route_proto_enumTypes[5]
}

func (x AccountLoginResponse_ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountLoginResponse_ErrCode.Descriptor instead.
func (AccountLoginResponse_ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{4, 1}
}

type EchoRequest_MSGID int32

const (
	EchoRequest_INVALID_MSGID EchoRequest_MSGID = 0
	EchoRequest_ID            EchoRequest_MSGID = 104
)

// Enum value maps for EchoRequest_MSGID.
var (
	EchoRequest_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		104: "ID",
	}
	EchoRequest_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            104,
	}
)

func (x EchoRequest_MSGID) Enum() *EchoRequest_MSGID {
	p := new(EchoRequest_MSGID)
	*p = x
	return p
}

func (x EchoRequest_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EchoRequest_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_route_proto_enumTypes[6].Descriptor()
}

func (EchoRequest_MSGID) Type() protoreflect.EnumType {
	return &file_proto_route_proto_enumTypes[6]
}

func (x EchoRequest_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EchoRequest_MSGID.Descriptor instead.
func (EchoRequest_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{5, 0}
}

type EchoResponse_MSGID int32

const (
	EchoResponse_INVALID_MSGID EchoResponse_MSGID = 0
	EchoResponse_ID            EchoResponse_MSGID = 105
)

// Enum value maps for EchoResponse_MSGID.
var (
	EchoResponse_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		105: "ID",
	}
	EchoResponse_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            105,
	}
)

func (x EchoResponse_MSGID) Enum() *EchoResponse_MSGID {
	p := new(EchoResponse_MSGID)
	*p = x
	return p
}

func (x EchoResponse_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EchoResponse_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_route_proto_enumTypes[7].Descriptor()
}

func (EchoResponse_MSGID) Type() protoreflect.EnumType {
	return &file_proto_route_proto_enumTypes[7]
}

func (x EchoResponse_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EchoResponse_MSGID.Descriptor instead.
func (EchoResponse_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{6, 0}
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_route_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_route_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errcode LoginResponse_ErrCode `protobuf:"varint,1,opt,name=errcode,proto3,enum=route.LoginResponse_ErrCode" json:"errcode,omitempty"`
	Uinfo   *UserInfo             `protobuf:"bytes,2,opt,name=uinfo,proto3" json:"uinfo,omitempty"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_route_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetErrcode() LoginResponse_ErrCode {
	if x != nil {
		return x.Errcode
	}
	return LoginResponse_ok
}

func (x *LoginResponse) GetUinfo() *UserInfo {
	if x != nil {
		return x.Uinfo
	}
	return nil
}

type AccountLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AccountLoginRequest) Reset() {
	*x = AccountLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_route_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountLoginRequest) ProtoMessage() {}

func (x *AccountLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountLoginRequest.ProtoReflect.Descriptor instead.
func (*AccountLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{3}
}

func (x *AccountLoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AccountLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AccountLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errcode AccountLoginResponse_ErrCode `protobuf:"varint,1,opt,name=errcode,proto3,enum=route.AccountLoginResponse_ErrCode" json:"errcode,omitempty"`
	Uinfo   *UserInfo                    `protobuf:"bytes,2,opt,name=uinfo,proto3" json:"uinfo,omitempty"`
}

func (x *AccountLoginResponse) Reset() {
	*x = AccountLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_route_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountLoginResponse) ProtoMessage() {}

func (x *AccountLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountLoginResponse.ProtoReflect.Descriptor instead.
func (*AccountLoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{4}
}

func (x *AccountLoginResponse) GetErrcode() AccountLoginResponse_ErrCode {
	if x != nil {
		return x.Errcode
	}
	return AccountLoginResponse_ok
}

func (x *AccountLoginResponse) GetUinfo() *UserInfo {
	if x != nil {
		return x.Uinfo
	}
	return nil
}

type EchoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_route_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{5}
}

func (x *EchoRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_route_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{6}
}

func (x *EchoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_route_proto protoreflect.FileDescriptor

var file_proto_route_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x22, 0x1c, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x48, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x22,
	0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44,
	0x10, 0x64, 0x22, 0xc8, 0x01, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x0a, 0x05,
	0x75, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x75, 0x69,
	0x6e, 0x66, 0x6f, 0x22, 0x22, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x10, 0x00, 0x12,
	0x06, 0x0a, 0x02, 0x49, 0x44, 0x10, 0x65, 0x22, 0x34, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x6f, 0x6b, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x75, 0x6e,
	0x6b, 0x6f, 0x77, 0x6e, 0x5f, 0x65, 0x72, 0x72, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x69, 0x6e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x10, 0x0b, 0x22, 0x6f, 0x0a,
	0x13, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x22, 0x0a, 0x05, 0x4d, 0x53,
	0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d,
	0x53, 0x47, 0x49, 0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44, 0x10, 0x66, 0x22, 0xd6,
	0x01, 0x0a, 0x14, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x65,
	0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x75, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x75, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x22, 0x0a,
	0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49,
	0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44, 0x10,
	0x67, 0x22, 0x34, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06, 0x0a, 0x02,
	0x6f, 0x6b, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x75, 0x6e, 0x6b, 0x6f, 0x77, 0x6e, 0x5f, 0x65,
	0x72, 0x72, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x10, 0x0b, 0x22, 0x43, 0x0a, 0x0b, 0x45, 0x63, 0x68, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x22, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49,
	0x44, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47,
	0x49, 0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44, 0x10, 0x68, 0x22, 0x44, 0x0a, 0x0c,
	0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x22,
	0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44,
	0x10, 0x69, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_route_proto_rawDescOnce sync.Once
	file_proto_route_proto_rawDescData = file_proto_route_proto_rawDesc
)

func file_proto_route_proto_rawDescGZIP() []byte {
	file_proto_route_proto_rawDescOnce.Do(func() {
		file_proto_route_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_route_proto_rawDescData)
	})
	return file_proto_route_proto_rawDescData
}

var file_proto_route_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_proto_route_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_route_proto_goTypes = []interface{}{
	(LoginRequest_MSGID)(0),           // 0: route.LoginRequest.MSGID
	(LoginResponse_MSGID)(0),          // 1: route.LoginResponse.MSGID
	(LoginResponse_ErrCode)(0),        // 2: route.LoginResponse.ErrCode
	(AccountLoginRequest_MSGID)(0),    // 3: route.AccountLoginRequest.MSGID
	(AccountLoginResponse_MSGID)(0),   // 4: route.AccountLoginResponse.MSGID
	(AccountLoginResponse_ErrCode)(0), // 5: route.AccountLoginResponse.ErrCode
	(EchoRequest_MSGID)(0),            // 6: route.EchoRequest.MSGID
	(EchoResponse_MSGID)(0),           // 7: route.EchoResponse.MSGID
	(*UserInfo)(nil),                  // 8: route.UserInfo
	(*LoginRequest)(nil),              // 9: route.LoginRequest
	(*LoginResponse)(nil),             // 10: route.LoginResponse
	(*AccountLoginRequest)(nil),       // 11: route.AccountLoginRequest
	(*AccountLoginResponse)(nil),      // 12: route.AccountLoginResponse
	(*EchoRequest)(nil),               // 13: route.EchoRequest
	(*EchoResponse)(nil),              // 14: route.EchoResponse
}
var file_proto_route_proto_depIdxs = []int32{
	2, // 0: route.LoginResponse.errcode:type_name -> route.LoginResponse.ErrCode
	8, // 1: route.LoginResponse.uinfo:type_name -> route.UserInfo
	5, // 2: route.AccountLoginResponse.errcode:type_name -> route.AccountLoginResponse.ErrCode
	8, // 3: route.AccountLoginResponse.uinfo:type_name -> route.UserInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_route_proto_init() }
func file_proto_route_proto_init() {
	if File_proto_route_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_route_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_route_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_route_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_route_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_route_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_route_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_route_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_route_proto_rawDesc,
			NumEnums:      8,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_route_proto_goTypes,
		DependencyIndexes: file_proto_route_proto_depIdxs,
		EnumInfos:         file_proto_route_proto_enumTypes,
		MessageInfos:      file_proto_route_proto_msgTypes,
	}.Build()
	File_proto_route_proto = out.File
	file_proto_route_proto_rawDesc = nil
	file_proto_route_proto_goTypes = nil
	file_proto_route_proto_depIdxs = nil
}
